#include "../Header/Cheat Functions/FiberMain.h"

// https://wiki.rage.mp/index.php?title=Weapons
const std::vector<WeaponHashesStruct> Cheat::GameArrays::WeaponsHashList = {
	{ "Knife", 0x99B507EA					}, //WeaponKnife
	{ "Nightstick", 0x678B81B1				}, //WeaponNightstick
	{ "Hammer", 0x4E875F73					}, //WeaponHammer
	{ "Bat", 0x958A4A8F						}, //WeaponBat
	{ "Golf Club", 0x440E4788				}, //WeaponGolfClub
	{ "Crowbar", 0x84BD7BFD					}, //WeaponCrowbar
	{ "Pistol", 0x1B06D571					}, //WeaponPistol
	{ "Combat Pistol", 0x5EF9FEC4			}, //WeaponCombatPistol
	{ "AP Pistol", 0x22D8FE39				}, //WeaponAPPistol
	{ "Pistol .50", 0x99AEEB3B				}, //WeaponPistol50
	{ "Micro SMG", 0x13532244				}, //WeaponMicroSMG
	{ "SMG", 0x2BE6766B						}, //WeaponSMG
	{ "Assault SMG", 0xEFE7E2DF				}, //WeaponAssaultSMG
	{ "Combat PDW", 0x0A3D4D34				}, //WeaponCombatPDW
	{ "Assault Rifle", 0xBFEFFF6D			}, //WeaponAssaultRifle
	{ "Carbine Rifle", 0x83BF0278			}, //WeaponCarbineRifle
	{ "Advanced Rifle", 0xAF113F99			}, //WeaponAdvancedRifle
	{ "MG", 0x9D07F764						}, //WeaponMG
	{ "Combat MG", 0x7FD62962				}, //WeaponCombatMG
	{ "Pump Shotgun", 0x1D073A89			}, //WeaponPumpShotgun
	{ "Saw-Off Shotgun", 0x7846A318			}, //WeaponSawnOffShotgun
	{ "Assault Shotgun", 0xE284C527			}, //WeaponAssaultShotgun
	{ "Bullpup Shotgun", 0x9D61E50F			}, //WeaponBullpupShotgun
	{ "Stun Gun", 0x3656C8C1				}, //WeaponStunGun
	{ "Sniper Rifle", 0x5FC3C11				}, //WeaponSniperRifle
	{ "Heavy Sniper", 0xC472FE2				}, //WeaponHeavySniper
	{ "Grenade Launcher", 0xA284510B		}, //WeaponGrenadeLauncher
	{ "Grenade Launcher (Smoke)", 0x4DD2DC56}, //WeaponGrenadeLauncherSmoke
	{ "RPG", 0xB1CA77B1						}, //WeaponRPG
	{ "Minigun", 0x42BF8A85					}, //WeaponMinigun
	{ "Grenade", 0x93E220BD					}, //WeaponGrenade
	{ "Sticky Bomb", 0x2C3731D9				}, //WeaponStickyBomb
	{ "Smoke Grenade", 0xFDBC8A50			}, //WeaponSmokeGrenade
	{ "BZ Gas", 0xA0973D5E					}, //WeaponBZGas
	{ "Molotov", 0x24B17070					}, //WeaponMolotov
	{ "Fire Extinguisher", 0x60EC506		}, //WeaponFireExtinguisher
	{ "Petrol Can", 0x34A67B97				}, //WeaponPetrolCan
	{ "SNS Pistol", 0xBFD21232				}, //WeaponSNSPistol
	{ "Special Carbine", 0xC0A3098D			}, //WeaponSpecialCarbine
	{ "Heavy Pistol", 0xD205520E			}, //WeaponHeavyPistol
	{ "Bullpup Rifle", 0x7F229F94			}, //WeaponBullpupRifle
	{ "Homing Launcher", 0x63AB0442			}, //WeaponHomingLauncher
	{ "Proximity Mine", 0xAB564B93			}, //WeaponProximityMine
	{ "Snowball", 0x787F0BB					}, //WeaponSnowball
	{ "Vintage Pistol", 0x83839C4			}, //WeaponVintagePistol
	{ "Dagger", 0x92A27487					}, //WeaponDagger
	{ "Firework", 0x7F7497E5				}, //WeaponFirework
	{ "Musket", 0xA89CB99E					}, //WeaponMusket
	{ "Marksman Rifle", 0xC734385A			}, //WeaponMarksmanRifle
	{ "Heavy Shotgun", 0x3AABBBAA			}, //WeaponHeavyShotgun
	{ "Gusenberg", 0x61012683				}, //WeaponGusenberg
	{ "Hatchet", 0xF9DCBF2D					}, //WeaponHatchet
	{ "Rail Gun", 0x6D544C99				}, //WeaponRailgun
	{ "Unarmed", 0xA2719263					}, //WeaponUnarmed
	{ "Bottle", 0xF9E6AA4B					}, //WeaponBottle
	{ "Flashlight", 0x8BB05FD7				}, //WeaponFlashlight
	{ "Knuckle", 0xD8DF3C3C					}, //WeaponKnuckle
	{ "Machete", 0xDD5DF8D9					}, //WeaponMachete
	{ "Switch Blade", 0xDFE37640			}, //WeaponSwitchBlade
	{ "Wrench", 0x19044EE0					}, //WeaponWrench
	{ "Battle Axe", 0xCD274149				}, //WeaponBattleAxe
	{ "Pool Cue", 0x94117305				}, //WeaponPoolCue
	{ "Stone Hatchet", 0x3813FC08			}, //WeaponStoneHatchet
	{ "Pistol Mk2", 0xBFE256D4				}, //WeaponPistolMk2
	{ "SNS Pistol Mk2", 0x88374054			}, //WeaponSNSPistolMk2
	{ "Flare Gun", 0x47757124				}, //WeaponFlareGun
	{ "Marksman Pistol", 0xDC4DB296			}, //WeaponMarksmanPistol
	{ "Revolver", 0xC1B3C3D1				}, //WeaponRevolver
	{ "Revolver Mk2", 0xCB96392F			}, //WeaponRevolverMk2
	{ "Double Action", 0x97EA20B8			}, //WeaponDoubleAction
	{ "Ray Pistol", 0xAF3696A1				}, //WeaponRayPistol
	{ "Ceramic Pistol", 0x2B5EF5EC			}, //WeaponCeramicPistol
	{ "Navy Revolver", 0x917F6C8C			}, //WeaponNavyRevolver
	{ "Gadget Pistol", 0x57A4368C			}, //WeaponGadgetPistol
	{ "SMG Mk2", 0x78A97CD0					}, //WeaponSMGMk2
	{ "Machine Pistol", 0xDB1AA450			}, //WeaponMachinePistol
	{ "Mini SMG", 0xBD248B55				}, //WeaponMiniSMG
	{ "Ray Carbine", 0x476BF155				}, //WeaponRayCarbine
	{ "Pump Shotgun Mk2", 0x555AF99A		}, //WeaponPumpshotgunMk2
	{ "Db Shotgun", 0xEF951FBB				}, //WeaponDbShotgun
	{ "Auto Shotgun", 0x12E82D3D			}, //WeaponAutoShotgun
	{ "Combat Shotgun", 0x5A96BA4			}, //WeaponCombatShotgun
	{ "Assault Rifle Mk2", 0x394F415C		}, //WeaponAssaultRifleMk2
	{ "Carbine Rifle Mk2", 0xFAD1F1C9		}, //WeaponCarbineRifleMk2
	{ "Special Carbine Mk2", 0x969C3D67		}, //WeaponSpecialCarbineMk2
	{ "Bullpup Rifle Mk2", 0x84D6FAFD		}, //WeaponBullpupRifleMk2
	{ "Compact Rifle", 0x624FE830			}, //WeaponCompactRifle
	{ "Military Rifle", 0x9D1F17E6			}, //WeaponMilitaryRifle
	{ "Combat MG", 0xDBBD7280				}, //WeaponCombatMG
	{ "Sniper Rifle", 0x05FC3C11			}, //WeaponSniperRifle
	{ "Heavy Sniper", 0x0C472FE2			}, //WeaponHeavySniper
	{ "Heavy Sniper Mk2", 0xA914799			}, //WeaponHeavySniperMk2
	{ "Marksman Rifle", 0xC734385A			}, //WeaponMarksmanRifle
	{ "Marksman Rifle Mk2", 0x6A6C02E0		}, //WeaponMarksmanRifleMk2
	{ "Compact Launcher", 0x0781FE4A		}, //WeaponCompactLauncher
	{ "Widowmaker", 0xB62D1F67				}, //WeaponWidowmaker
	{ "Pipe Bomb", 0xBA45E8B8				}, //WeaponPipeBomb
	{ "Ball", 0x23C9F95C					}, //WeaponBall
	{ "Flare", 0x497FACC3					}, //WeaponFlare
	{ "Parachute", 0xFBAB5776				}, //WeaponParachute
	{ "Fire Extinguisher", 0x060EC506		}, //WeaponFireExtinguisher
	{ "Hazard Can", 0xBA536372				}, //WeaponHazardCan
	{ "Fertilizer Can", 0x184140A1			}, //WeaponFertilizerCan	
	{ "Heavy Rifle", 0xC78D71B4				}, //WeaponHeavyRifle									
	{ "Compact EMP Launcher", 0xDB26713A	}, //WeaponEMPLauncher
	{ "StunGun MP", 0x45CD9CF3				}, //WeaponStunGunMP
	{ "Precision Rifle", 0x6E7DDDEC			}, //WeaponPrecisionRifle
	{ "Tactical Rifle", 0xD1D5F52B			}  //WeaponTecticalRifle
};

const std::vector<std::string> Cheat::GameArrays::PedModels = {
"A_C_Boar",
"A_C_Cat_01",
"A_C_Chickenhawk",
"A_C_Chimp",
"A_C_Chop",
"A_C_Chop_02",
"A_C_Cormorant",
"A_C_Cow",
"A_C_Coyote",
"A_C_Crow",
"A_C_Deer",
"A_C_Dolphin",
"A_C_Fish",
"A_C_Hen",
"A_C_HumpBack",
"A_C_Husky",
"A_C_KillerWhale",
"A_C_MtLion",
"A_C_Panther",
"A_C_Pig",
"A_C_Pigeon",
"A_C_Poodle",
"A_C_Pug",
"A_C_Rabbit_01",
"A_C_Rat",
"A_C_Retriever",
"A_C_Rhesus",
"A_C_Rottweiler",
"A_C_Seagull",
"A_C_SharkHammer",
"A_C_SharkTiger",
"A_C_shepherd",
"A_C_Stingray",
"A_C_Westy",
"A_F_M_Beach_01",
"A_F_M_BevHills_01",
"A_F_M_BevHills_02",
"A_F_M_BodyBuild_01",
"A_F_M_Business_02",
"A_F_M_Downtown_01",
"A_F_M_EastSA_01",
"A_F_M_EastSA_02",
"A_F_M_FatBla_01",
"A_F_M_FatCult_01",
"A_F_M_FatWhite_01",
"A_F_M_KTown_01",
"A_F_M_KTown_02",
"A_F_M_ProlHost_01",
"A_F_M_Salton_01",
"A_F_M_SkidRow_01",
"A_F_M_SouCent_01",
"A_F_M_SouCent_02",
"A_F_M_SouCentMC_01",
"A_F_M_Tourist_01",
"A_F_M_Tramp_01",
"A_F_M_TrampBeac_01",
"A_F_O_GenStreet_01",
"A_F_O_Indian_01",
"A_F_O_KTown_01",
"A_F_O_Salton_01",
"A_F_O_SouCent_01",
"A_F_O_SouCent_02",
"A_F_Y_Beach_01",
"A_F_Y_Beach_02",
"A_F_Y_BevHills_01",
"A_F_Y_BevHills_02",
"A_F_Y_BevHills_03",
"A_F_Y_BevHills_04",
"A_F_Y_Bevhills_05",
"A_F_Y_Business_01",
"A_F_Y_Business_02",
"A_F_Y_Business_03",
"A_F_Y_Business_04",
"A_F_Y_CarClub_01",
"A_F_Y_ClubCust_01",
"A_F_Y_ClubCust_02",
"A_F_Y_ClubCust_03",
"A_F_Y_ClubCust_04",
"A_F_Y_EastSA_01",
"A_F_Y_EastSA_02",
"A_F_Y_EastSA_03",
"A_F_Y_Epsilon_01",
"A_F_Y_FemaleAgent",
"A_F_Y_Fitness_01",
"A_F_Y_Fitness_02",
"A_F_Y_GenCasPat_01",
"A_F_Y_GenHot_01",
"A_F_Y_Golfer_01",
"A_F_Y_Hiker_01",
"A_F_Y_Hippie_01",
"A_F_Y_Hipster_01",
"A_F_Y_Hipster_02",
"A_F_Y_Hipster_03",
"A_F_Y_Hipster_04",
"A_F_Y_Indian_01",
"A_F_Y_Juggalo_01",
"A_F_Y_Runner_01",
"A_F_Y_RurMeth_01",
"A_F_Y_SCDressy_01",
"A_F_Y_Skater_01",
"A_F_Y_SmartCasPat_01",
"A_F_Y_SouCent_01",
"A_F_Y_SouCent_02",
"A_F_Y_SouCent_03",
"A_F_Y_StudioParty_01",
"A_F_Y_StudioParty_02",
"A_F_Y_Tennis_01",
"A_F_Y_Topless_01",
"A_F_Y_Tourist_01",
"A_F_Y_Tourist_02",
"A_F_Y_Vinewood_01",
"A_F_Y_Vinewood_02",
"A_F_Y_Vinewood_03",
"A_F_Y_Vinewood_04",
"A_F_Y_Yoga_01",
"A_M_M_ACult_01",
"A_M_M_AfriAmer_01",
"A_M_M_Beach_01",
"A_M_M_Beach_02",
"A_M_M_BevHills_01",
"A_M_M_BevHills_02",
"A_M_M_Business_01",
"A_M_M_EastSA_01",
"A_M_M_EastSA_02",
"A_M_M_Farmer_01",
"A_M_M_FatLatin_01",
"A_M_M_GenFat_01",
"A_M_M_GenFat_02",
"A_M_M_Golfer_01",
"A_M_M_HasJew_01",
"A_M_M_Hillbilly_01",
"A_M_M_Hillbilly_02",
"A_M_M_Indian_01",
"A_M_M_KTown_01",
"A_M_M_Malibu_01",
"A_M_M_MexCntry_01",
"A_M_M_MexLabor_01",
"A_M_M_MLCrisis_01",
"A_M_M_OG_Boss_01",
"A_M_M_Paparazzi_01",
"A_M_M_Polynesian_01",
"A_M_M_ProlHost_01",
"A_M_M_RurMeth_01",
"A_M_M_Salton_01",
"A_M_M_Salton_02",
"A_M_M_Salton_03",
"A_M_M_Salton_04",
"A_M_M_Skater_01",
"A_M_M_Skidrow_01",
"A_M_M_SoCenLat_01",
"A_M_M_SouCent_01",
"A_M_M_SouCent_02",
"A_M_M_SouCent_03",
"A_M_M_SouCent_04",
"A_M_M_StLat_02",
"A_M_M_StudioParty_01",
"A_M_M_Tennis_01",
"A_M_M_Tourist_01",
"A_M_M_Tramp_01",
"A_M_M_TrampBeac_01",
"A_M_M_TranVest_01",
"A_M_M_TranVest_02",
"A_M_O_ACult_01",
"A_M_O_ACult_02",
"A_M_O_Beach_01",
"A_M_O_Beach_02",
"A_M_O_GenStreet_01",
"A_M_O_KTown_01",
"A_M_O_Salton_01",
"A_M_O_SouCent_01",
"A_M_O_SouCent_02",
"A_M_O_SouCent_03",
"A_M_O_Tramp_01",
"A_M_Y_ACult_01",
"A_M_Y_ACult_02",
"A_M_Y_Beach_01",
"A_M_Y_Beach_02",
"A_M_Y_Beach_03",
"A_M_Y_Beach_04",
"A_M_Y_BeachVesp_01",
"A_M_Y_BeachVesp_02",
"A_M_Y_BevHills_01",
"A_M_Y_BevHills_02",
"A_M_Y_BreakDance_01",
"A_M_Y_BusiCas_01",
"A_M_Y_Business_01",
"A_M_Y_Business_02",
"A_M_Y_Business_03",
"A_M_Y_CarClub_01",
"A_M_Y_ClubCust_01",
"A_M_Y_ClubCust_02",
"A_M_Y_ClubCust_03",
"A_M_Y_ClubCust_04",
"A_M_Y_Cyclist_01",
"A_M_Y_DHill_01",
"A_M_Y_Downtown_01",
"A_M_Y_EastSA_01",
"A_M_Y_EastSA_02",
"A_M_Y_Epsilon_01",
"A_M_Y_Epsilon_02",
"A_M_Y_Gay_01",
"A_M_Y_Gay_02",
"A_M_Y_GenCasPat_01",
"A_M_Y_GenStreet_01",
"A_M_Y_GenStreet_02",
"A_M_Y_Golfer_01",
"A_M_Y_HasJew_01",
"A_M_Y_Hiker_01",
"A_M_Y_Hippy_01",
"A_M_Y_Hipster_01",
"A_M_Y_Hipster_02",
"A_M_Y_Hipster_03",
"A_M_Y_Indian_01",
"A_M_Y_Jetski_01",
"A_M_Y_Juggalo_01",
"A_M_Y_KTown_01",
"A_M_Y_KTown_02",
"A_M_Y_Latino_01",
"A_M_Y_MethHead_01",
"A_M_Y_MexThug_01",
"A_M_Y_MotoX_01",
"A_M_Y_MotoX_02",
"A_M_Y_MusclBeac_01",
"A_M_Y_MusclBeac_02",
"A_M_Y_Polynesian_01",
"A_M_Y_RoadCyc_01",
"A_M_Y_Runner_01",
"A_M_Y_Runner_02",
"A_M_Y_Salton_01",
"A_M_Y_Skater_01",
"A_M_Y_Skater_02",
"A_M_Y_SmartCasPat_01",
"A_M_Y_SouCent_01",
"A_M_Y_SouCent_02",
"A_M_Y_SouCent_03",
"A_M_Y_SouCent_04",
"A_M_Y_StBla_01",
"A_M_Y_StBla_02",
"A_M_Y_StLat_01",
"A_M_Y_StudioParty_01",
"A_M_Y_StWhi_01",
"A_M_Y_StWhi_02",
"A_M_Y_Sunbathe_01",
"A_M_Y_Surfer_01",
"A_M_Y_TattooCust_01",
"A_M_Y_VinDouche_01",
"A_M_Y_Vinewood_01",
"A_M_Y_Vinewood_02",
"A_M_Y_Vinewood_03",
"A_M_Y_Vinewood_04",
"A_M_Y_Yoga_01",
"CS_AmandaTownley",
"CS_Andreas",
"cs_ashley",
"CS_Bankman",
"CS_Barry",
"CS_Beverly",
"CS_Brad",
"CS_BradCadaver",
"CS_Carbuyer",
"CS_Casey",
"CS_ChengSr",
"CS_ChrisFormage",
"CS_Clay",
"CS_Dale",
"CS_DaveNorton",
"cs_debra",
"cs_denise",
"CS_Devin",
"CS_Dom",
"CS_Dreyfuss",
"CS_DrFriedlander",
"CS_Fabien",
"CS_FBISuit_01",
"CS_Floyd",
"CS_Guadalope",
"cs_gurk",
"CS_Hunter",
"CS_Janet",
"CS_JewelAss",
"CS_JimmyBoston",
"CS_JimmyDiSanto",
"CS_JimmyDiSanto2",
"CS_JoeMinuteMan",
"CS_JohnnyKlebitz",
"CS_Josef",
"CS_Josh",
"CS_Karen_Daniels",
"CS_LamarDavis",
"CS_LamarDavis_02",
"CS_Lazlow",
"CS_Lazlow_2",
"CS_LesterCrest",
"CS_LesterCrest_2",
"CS_LesterCrest_3",
"CS_LifeInvad_01",
"CS_Magenta",
"CS_Manuel",
"CS_Marnie",
"CS_MartinMadrazo",
"CS_MaryAnn",
"CS_Michelle",
"CS_Milton",
"CS_Molly",
"CS_MovPremF_01",
"CS_MovPremMale",
"CS_MRK",
"CS_MRS_Thornhill",
"CS_MrsPhillips",
"CS_Natalia",
"CS_NervousRon",
"CS_Nigel",
"CS_Old_Man1A",
"CS_Old_Man2",
"CS_Omega",
"CS_Orleans",
"CS_Paper",
"CS_Patricia",
"CS_Patricia_02",
"CS_Priest",
"CS_ProlSec_02",
"CS_RussianDrunk",
"CS_SiemonYetarian",
"CS_Solomon",
"CS_SteveHains",
"CS_Stretch",
"CS_Tanisha",
"CS_TaoCheng",
"CS_TaoCheng2",
"CS_TaosTranslator",
"CS_TaosTranslator2",
"CS_TennisCoach",
"CS_Terry",
"CS_Tom",
"CS_TomEpsilon",
"CS_TracyDiSanto",
"CS_Wade",
"CS_Zimbor",
"CSB_Abigail",
"CSB_Agatha",
"CSB_Agent",
"CSB_Alan",
"CSB_Anita",
"CSB_Anton",
"CSB_ARY",
"CSB_ARY_02",
"CSB_Avery",
"CSB_AviSchwartzman_02",
"CSB_Avon",
"CSB_Ballas_Leader",
"CSB_BallasOG",
"CSB_Billionaire",
"CSB_Bogdan",
"CSB_Bride",
"CSB_Brucie2",
"CSB_Bryony",
"CSB_BurgerDrug",
"CSB_Car3guy1",
"CSB_Car3guy2",
"CSB_Celeb_01",
"CSB_Chef",
"CSB_Chef2",
"CSB_Chin_goon",
"CSB_Cletus",
"CSB_Cop",
"CSB_Customer",
"CSB_Denise_friend",
"CSB_Dix",
"CSB_DJBlaMadon",
"CSB_DrugDealer",
"CSB_EnglishDave",
"CSB_EnglishDave_02",
"CSB_FOS_rep",
"CSB_G",
"CSB_GeorginaCheng",
"CSB_Golfer_A",
"CSB_Golfer_B",
"CSB_Groom",
"CSB_Grove_str_dlr",
"CSB_Gustavo",
"CSB_Hao",
"CSB_Hao_02",
"CSB_HelmsmanPavel",
"CSB_Huang",
"CSB_Hugh",
"CSB_Imani",
"CSB_Imran",
"CSB_IslDJ_00",
"CSB_IslDJ_01",
"CSB_ISLDJ_02",
"CSB_IslDJ_03",
"CSB_IslDJ_04",
"CSB_JackHowitzer",
"CSB_Janitor",
"CSB_JIO",
"CSB_JIO_02",
"CSB_Johnny_Guns",
"CSB_JuanStrickler",
"CSB_Maude",
"CSB_MiguelMadrazo",
"CSB_Mimi",
"CSB_MJO",
"CSB_MJO_02",
"CSB_Money",
"CSB_Moodyman_02",
"CSB_MP_Agent14",
"CSB_Mrs_R",
"CSB_Musician_00",
"CSB_MWeather",
"CSB_Ortega",
"CSB_Oscar",
"CSB_Paige",
"CSB_Party_Promo",
"CSB_Popov",
"CSB_PornDudes",
"CSB_PrologueDriver",
"CSB_ProlSec",
"CSB_Ramp_gang",
"CSB_Ramp_hic",
"CSB_Ramp_hipster",
"CSB_Ramp_marine",
"CSB_Ramp_mex",
"CSB_Rashcosvki",
"CSB_Reporter",
"CSB_Req_Officer",
"CSB_RoccoPelosi",
"CSB_Screen_Writer",
"CSB_Security_A",
"CSB_Sessanta",
"CSB_Sol",
"CSB_SoundEng_00",
"CSB_SSS",
"CSB_Stripper_01",
"CSB_Stripper_02",
"CSB_TalCC",
"CSB_TalMM",
"CSB_Thornton",
"CSB_TomCasino",
"CSB_Tonya",
"CSB_TonyPrince",
"CSB_TrafficWarden",
"CSB_Undercover",
"CSB_Vagos_Leader",
"CSB_VagSpeak",
"CSB_Vernon",
"CSB_Vincent",
"CSB_Vincent_2",
"CSB_Wendy",
"G_F_ImportExport_01",
"G_F_Y_ballas_01",
"G_F_Y_Families_01",
"G_F_Y_Lost_01",
"G_F_Y_Vagos_01",
"G_M_ImportExport_01",
"G_M_M_ArmBoss_01",
"G_M_M_ArmGoon_01",
"G_M_M_ArmLieut_01",
"G_M_M_CartelGuards_01",
"G_M_M_CartelGuards_02",
"G_M_M_CasRN_01",
"G_M_M_ChemWork_01",
"G_M_M_ChiBoss_01",
"G_M_M_ChiCold_01",
"G_M_M_ChiGoon_01",
"G_M_M_ChiGoon_02",
"G_M_M_Goons_01",
"G_M_M_KorBoss_01",
"G_M_M_MexBoss_01",
"G_M_M_MexBoss_02",
"G_M_M_Prisoners_01",
"G_M_M_Slasher_01",
"G_M_Y_ArmGoon_02",
"G_M_Y_Azteca_01",
"G_M_Y_BallaEast_01",
"G_M_Y_BallaOrig_01",
"G_M_Y_BallaSout_01",
"G_M_Y_FamCA_01",
"G_M_Y_FamDNF_01",
"G_M_Y_FamFor_01",
"G_M_Y_Korean_01",
"G_M_Y_Korean_02",
"G_M_Y_KorLieut_01",
"G_M_Y_Lost_01",
"G_M_Y_Lost_02",
"G_M_Y_Lost_03",
"G_M_Y_MexGang_01",
"G_M_Y_MexGoon_01",
"G_M_Y_MexGoon_02",
"G_M_Y_MexGoon_03",
"G_M_Y_PoloGoon_01",
"G_M_Y_PoloGoon_02",
"G_M_Y_SalvaBoss_01",
"G_M_Y_SalvaGoon_01",
"G_M_Y_SalvaGoon_02",
"G_M_Y_SalvaGoon_03",
"G_M_Y_StrPunk_01",
"G_M_Y_StrPunk_02",
"HC_Driver",
"HC_Gunman",
"HC_Hacker",
"IG_Abigail",
"IG_Agatha",
"IG_Agent",
"IG_AmandaTownley",
"IG_Andreas",
"IG_ARY",
"IG_ARY_02",
"IG_Ashley",
"IG_Avery",
"IG_AviSchwartzman_02",
"IG_Avon",
"IG_Ballas_Leader",
"IG_BallasOG",
"IG_Bankman",
"IG_Barry",
"IG_Benny",
"IG_Benny_02",
"IG_BestMen",
"IG_Beverly",
"IG_Billionaire",
"IG_Brad",
"IG_Bride",
"IG_Brucie2",
"IG_Car3guy1",
"IG_Car3guy2",
"IG_Casey",
"IG_Celeb_01",
"IG_Chef",
"IG_Chef2",
"IG_ChengSr",
"IG_ChrisFormage",
"IG_Clay",
"IG_ClayPain",
"IG_Cletus",
"IG_Dale",
"IG_DaveNorton",
"IG_Denise",
"IG_Devin",
"IG_Dix",
"IG_DJBlaMadon",
"IG_DJBlamRupert",
"IG_DJBlamRyanH",
"IG_DJBlamRyanS",
"IG_DJDixManager",
"IG_DJGeneric_01",
"IG_DJSolFotios",
"IG_DJSolJakob",
"IG_DJSolManager",
"IG_DJSolMike",
"IG_DJSolRobT",
"IG_DJTalAurelia",
"IG_DJTalIgnazio",
"IG_Dom",
"IG_Dreyfuss",
"IG_DrFriedlander",
"IG_DrugDealer",
"IG_EnglishDave",
"IG_EnglishDave_02",
"IG_Entourage_A",
"IG_Entourage_B",
"IG_Fabien",
"IG_FBISuit_01",
"IG_Floyd",
"IG_G",
"IG_GeorginaCheng",
"IG_Golfer_A",
"IG_Golfer_B",
"IG_Groom",
"IG_Gustavo",
"IG_Hao",
"IG_Hao_02",
"IG_HelmsmanPavel",
"IG_Huang",
"IG_Hunter",
"IG_Imani",
"IG_IslDJ_00",
"IG_IslDJ_01",
"IG_IslDJ_02",
"IG_IslDJ_03",
"IG_IslDJ_04",
"IG_ISLDJ_04_D_01",
"IG_ISLDJ_04_D_02",
"IG_ISLDJ_04_E_01",
"IG_Jackie",
"IG_Janet",
"ig_JAY_Norris",
"IG_JewelAss",
"IG_JimmyBoston",
"IG_JimmyBoston_02",
"IG_JimmyDiSanto",
"IG_JimmyDiSanto2",
"IG_JIO",
"IG_JIO_02",
"IG_JoeMinuteMan",
"IG_Johnny_Guns",
"ig_JohnnyKlebitz",
"IG_Josef",
"IG_Josh",
"IG_JuanStrickler",
"IG_Karen_Daniels",
"IG_Kaylee",
"IG_KerryMcIntosh",
"IG_KerryMcIntosh_02",
"IG_Lacey_Jones_02",
"IG_LamarDavis",
"IG_LamarDavis_02",
"IG_Lazlow",
"IG_Lazlow_2",
"IG_LesterCrest",
"IG_LesterCrest_2",
"IG_LesterCrest_3",
"IG_LifeInvad_01",
"IG_LifeInvad_02",
"IG_LilDee",
"IG_Magenta",
"IG_Malc",
"IG_Manuel",
"IG_Marnie",
"IG_MaryAnn",
"IG_Maude",
"IG_Michelle",
"IG_MiguelMadrazo",
"IG_Milton",
"IG_Mimi",
"IG_MJO",
"IG_MJO_02",
"IG_Molly",
"IG_Money",
"IG_Moodyman_02",
"IG_MP_Agent14",
"IG_MRK",
"IG_MRS_Thornhill",
"IG_MrsPhillips",
"IG_Musician_00",
"IG_Natalia",
"IG_NervousRon",
"IG_Nigel",
"IG_Old_Man1A",
"IG_Old_Man2",
"IG_OldRichGuy",
"IG_Omega",
"IG_ONeil",
"IG_Orleans",
"IG_Ortega",
"IG_Paige",
"IG_Paper",
"IG_Party_Promo",
"IG_Patricia",
"IG_Patricia_02",
"IG_Pilot",
"IG_Popov",
"IG_Priest",
"IG_ProlSec_02",
"IG_Ramp_Gang",
"IG_Ramp_Hic",
"IG_Ramp_Hipster",
"IG_Ramp_Mex",
"IG_Rashcosvki",
"IG_Req_Officer",
"IG_RoccoPelosi",
"IG_RussianDrunk",
"IG_Sacha",
"IG_Screen_Writer",
"IG_Security_A",
"IG_Sessanta",
"IG_SiemonYetarian",
"IG_Sol",
"IG_Solomon",
"IG_SoundEng_00",
"IG_SSS",
"IG_SteveHains",
"IG_Stretch",
"IG_TalCC",
"IG_Talina",
"IG_TalMM",
"IG_Tanisha",
"IG_TaoCheng",
"IG_TaoCheng2",
"IG_TaosTranslator",
"IG_TaosTranslator2",
"ig_TennisCoach",
"IG_Terry",
"IG_Thornton",
"IG_TomCasino",
"IG_TomEpsilon",
"IG_Tonya",
"IG_TonyPrince",
"IG_TracyDiSanto",
"IG_TrafficWarden",
"IG_TylerDix",
"IG_TylerDix_02",
"IG_Vagos_Leader",
"IG_VagSpeak",
"IG_Vernon",
"IG_Vincent",
"IG_Vincent_2",
"IG_Vincent_3",
"IG_Wade",
"IG_Wendy",
"IG_Zimbor",
"MP_F_BennyMech_01",
"MP_F_BoatStaff_01",
"MP_F_CarDesign_01",
"MP_F_CHBar_01",
"MP_F_Cocaine_01",
"MP_F_Counterfeit_01",
"MP_F_DeadHooker",
"MP_F_ExecPA_01",
"MP_F_ExecPA_02",
"MP_F_Forgery_01",
"MP_F_Freemode_01",
"MP_F_HeliStaff_01",
"MP_F_Meth_01",
"MP_F_Misty_01",
"MP_F_StripperLite",
"MP_F_Weed_01",
"MP_G_M_Pros_01",
"MP_HeadTargets",
"MP_M_AvonGoon",
"MP_M_BoatStaff_01",
"MP_M_BogdanGoon",
"MP_M_Claude_01",
"MP_M_Cocaine_01",
"MP_M_Counterfeit_01",
"MP_M_ExArmy_01",
"MP_M_ExecPA_01",
"MP_M_FamDD_01",
"MP_M_FIBSec_01",
"MP_M_Forgery_01",
"MP_M_Freemode_01",
"MP_M_G_VagFun_01",
"MP_M_Marston_01",
"MP_M_Meth_01",
"MP_M_Niko_01",
"MP_M_SecuroGuard_01",
"MP_M_ShopKeep_01",
"MP_M_WareMech_01",
"MP_M_WeapExp_01",
"MP_M_WeapWork_01",
"MP_M_Weed_01",
"MP_S_M_Armoured_01",
"P_Franklin_02",
"Player_One",
"Player_Two",
"Player_Zero",
"S_F_M_Autoshop_01",
"S_F_M_Fembarber",
"S_F_M_Maid_01",
"S_F_M_RetailStaff_01",
"S_F_M_Shop_HIGH",
"S_F_M_StudioAssist_01",
"S_F_M_SweatShop_01",
"S_F_Y_AirHostess_01",
"S_F_Y_Bartender_01",
"S_F_Y_Baywatch_01",
"S_F_Y_BeachBarStaff_01",
"S_F_Y_Casino_01",
"S_F_Y_ClubBar_01",
"S_F_Y_ClubBar_02",
"S_F_Y_Cop_01",
"S_F_Y_Factory_01",
"S_F_Y_Hooker_01",
"S_F_Y_Hooker_02",
"S_F_Y_Hooker_03",
"S_F_Y_Migrant_01",
"S_F_Y_MovPrem_01",
"S_F_Y_Ranger_01",
"S_F_Y_Scrubs_01",
"S_F_Y_Sheriff_01",
"S_F_Y_Shop_LOW",
"S_F_Y_Shop_MID",
"S_F_Y_Stripper_01",
"S_F_Y_Stripper_02",
"S_F_Y_StripperLite",
"S_F_Y_SweatShop_01",
"S_M_M_AmmuCountry",
"S_M_M_Armoured_01",
"S_M_M_Armoured_02",
"S_M_M_AutoShop_01",
"S_M_M_AutoShop_02",
"S_M_M_Autoshop_03",
"S_M_M_Bouncer_01",
"S_M_M_Bouncer_02",
"S_M_M_CCrew_01",
"S_M_M_ChemSec_01",
"S_M_M_CIASec_01",
"S_M_M_CntryBar_01",
"S_M_M_DockWork_01",
"S_M_M_Doctor_01",
"S_M_M_DrugProcess_01",
"S_M_M_FIBOffice_01",
"S_M_M_FIBOffice_02",
"S_M_M_FIBSec_01",
"S_M_M_FieldWorker_01",
"S_M_M_Gaffer_01",
"S_M_M_Gardener_01",
"S_M_M_GenTransport",
"S_M_M_HairDress_01",
"S_M_M_HighSec_01",
"S_M_M_HighSec_02",
"S_M_M_HighSec_03",
"S_M_M_HighSec_04",
"S_M_M_HighSec_05",
"S_M_M_Janitor",
"S_M_M_LatHandy_01",
"S_M_M_LifeInvad_01",
"S_M_M_Linecook",
"S_M_M_LSMetro_01",
"S_M_M_Mariachi_01",
"S_M_M_Marine_01",
"S_M_M_Marine_02",
"S_M_M_Migrant_01",
"S_M_M_MovAlien_01",
"S_M_M_MovPrem_01",
"S_M_M_MovSpace_01",
"S_M_M_Paramedic_01",
"S_M_M_Pilot_01",
"S_M_M_Pilot_02",
"S_M_M_Postal_01",
"S_M_M_Postal_02",
"S_M_M_PrisGuard_01",
"S_M_M_RaceOrg_01",
"S_M_M_Scientist_01",
"S_M_M_Security_01",
"S_M_M_SnowCop_01",
"S_M_M_StrPerf_01",
"S_M_M_StrPreach_01",
"S_M_M_StrVend_01",
"S_M_M_StudioAssist_02",
"S_M_M_StudioProd_01",
"S_M_M_StudioSouEng_02",
"S_M_M_Tattoo_01",
"S_M_M_Trucker_01",
"S_M_M_UPS_01",
"S_M_M_UPS_02",
"S_M_O_Busker_01",
"S_M_Y_AirWorker",
"S_M_Y_AmmuCity_01",
"S_M_Y_ArmyMech_01",
"S_M_Y_Autopsy_01",
"S_M_Y_Barman_01",
"S_M_Y_BayWatch_01",
"S_M_Y_BlackOps_01",
"S_M_Y_BlackOps_02",
"S_M_Y_BlackOps_03",
"S_M_Y_BusBoy_01",
"S_M_Y_Casino_01",
"S_M_Y_Chef_01",
"S_M_Y_Clown_01",
"S_M_Y_ClubBar_01",
"S_M_Y_Construct_01",
"S_M_Y_Construct_02",
"S_M_Y_Cop_01",
"S_M_Y_Dealer_01",
"S_M_Y_DevinSec_01",
"S_M_Y_DockWork_01",
"S_M_Y_Doorman_01",
"S_M_Y_DWService_01",
"S_M_Y_DWService_02",
"S_M_Y_Factory_01",
"S_M_Y_Fireman_01",
"S_M_Y_Garbage",
"S_M_Y_Grip_01",
"S_M_Y_HwayCop_01",
"S_M_Y_Marine_01",
"S_M_Y_Marine_02",
"S_M_Y_Marine_03",
"S_M_Y_Mime",
"S_M_Y_PestCont_01",
"S_M_Y_Pilot_01",
"S_M_Y_PrisMuscl_01",
"S_M_Y_Prisoner_01",
"S_M_Y_Ranger_01",
"S_M_Y_Robber_01",
"S_M_Y_Sheriff_01",
"S_M_Y_Shop_MASK",
"S_M_Y_StrVend_01",
"S_M_Y_Swat_01",
"S_M_Y_USCG_01",
"S_M_Y_Valet_01",
"S_M_Y_Waiter_01",
"S_M_Y_WareTech_01",
"S_M_Y_WestSec_01",
"S_M_Y_WestSec_02",
"S_M_Y_WinClean_01",
"S_M_Y_XMech_01",
"S_M_Y_XMech_02",
"S_M_Y_XMech_02_MP",
"U_F_M_CasinoCash_01",
"U_F_M_CasinoShop_01",
"U_F_M_Corpse_01",
"U_F_M_Debbie_01",
"U_F_M_Drowned_01",
"U_F_M_Miranda",
"U_F_M_Miranda_02",
"U_F_M_ProMourn_01",
"U_F_O_Carol",
"U_F_O_Eileen",
"U_F_O_MovieStar",
"U_F_O_ProlHost_01",
"U_F_Y_Beth",
"U_F_Y_BikerChic",
"U_F_Y_COMJane",
"U_F_Y_corpse_01",
"U_F_Y_corpse_02",
"U_F_Y_DanceBurl_01",
"U_F_Y_DanceLthr_01",
"U_F_Y_DanceRave_01",
"U_F_Y_HotPosh_01",
"U_F_Y_JewelAss_01",
"U_F_Y_Lauren",
"U_F_Y_Mistress",
"U_F_Y_PoppyMich",
"U_F_Y_PoppyMich_02",
"U_F_Y_Princess",
"U_F_Y_SpyActress",
"U_F_Y_Taylor",
"U_M_M_Aldinapoli",
"U_M_M_BankMan",
"U_M_M_BikeHire_01",
"U_M_M_Blane",
"U_M_M_Curtis",
"U_M_M_DOA_01",
"U_M_M_EdToh",
"U_M_M_FIBArchitect",
"U_M_M_FilmDirector",
"U_M_M_GlenStank_01",
"U_M_M_Griff_01",
"U_M_M_Jesus_01",
"U_M_M_JewelSec_01",
"U_M_M_JewelThief",
"U_M_M_MarkFost",
"U_M_M_PartyTarget",
"U_M_M_ProlSec_01",
"U_M_M_ProMourn_01",
"U_M_M_RivalPap",
"U_M_M_SpyActor",
"U_M_M_StreetArt_01",
"U_M_M_Vince",
"U_M_M_WillyFist",
"U_M_O_Dean",
"U_M_O_FilmNoir",
"U_M_O_FinGuru_01",
"U_M_O_TapHillBilly",
"U_M_O_Tramp_01",
"U_M_Y_Abner",
"U_M_Y_AntonB",
"U_M_Y_BabyD",
"U_M_Y_Baygor",
"U_M_Y_BurgerDrug_01",
"U_M_Y_Caleb",
"U_M_Y_Chip",
"U_M_Y_Corpse_01",
"U_M_Y_CroupThief_01",
"U_M_Y_Cyclist_01",
"U_M_Y_DanceBurl_01",
"U_M_Y_DanceLthr_01",
"U_M_Y_DanceRave_01",
"U_M_Y_FIBMugger_01",
"U_M_Y_Gabriel",
"U_M_Y_Guido_01",
"U_M_Y_GunVend_01",
"U_M_Y_Hippie_01",
"U_M_Y_ImpoRage",
"U_M_Y_Juggernaut_01",
"U_M_Y_Justin",
"U_M_Y_Mani",
"U_M_Y_MilitaryBum",
"U_M_Y_Paparazzi",
"U_M_Y_Party_01",
"U_M_Y_Pogo_01",
"U_M_Y_Prisoner_01",
"U_M_Y_ProlDriver_01",
"U_M_Y_RSRanger_01",
"U_M_Y_SBike",
"U_M_Y_SmugMech_01",
"U_M_Y_StagGrm_01",
"U_M_Y_Tattoo_01",
"U_M_Y_Ushi",
"U_M_Y_Zombie_01"
};

const std::vector<std::string> Cheat::GameArrays::BoatModels = {
	"DINGHY", "DINGHY2", "DINGHY3", "DINGHY4", "JETMAX",
	"MARQUIS", "PREDATOR", "SEASHARK", "SEASHARK2", "SEASHARK3",
	"SPEEDER", "SPEEDER2", "SQUALO", "SUBMERSIBLE", "SUBMERSIBLE2",
	"SUNTRAP", "TORO", "TORO2", "TROPIC", "TROPIC2",
	"TUG"
};
const std::vector<std::string> Cheat::GameArrays::CommercialModels = {
	"BENSON", "BIFF", "HAULER", "MULE", "MULE2",
	"MULE3", "PACKER", "PHANTOM", "POUNDER", "STOCKADE",
	"STOCKADE3"
};
const std::vector<std::string> Cheat::GameArrays::CompactsModels = {
	"BLISTA", "BRIOSO", "DILETTANTE", "DILETTANTE2", "ISSI2",
	"PANTO", "PRAIRIE", "RHAPSODY"
};
const std::vector<std::string> Cheat::GameArrays::CoupesModels = {
	"COGCABRIO", "EXEMPLAR", "F620", "FELON", "FELON2",
	"JACKAL", "ORACLE", "ORACLE2", "SENTINEL", "SENTINEL2",
	"WINDSOR", "WINDSOR2", "ZION", "ZION2"
};
const std::vector<std::string> Cheat::GameArrays::CycleModels = {
	"BMX", "CRUISER", "FIXTER", "SCORCHER", "TRIBIKE",
	"TRIBIKE2", "TRIBIKE3"
};
const std::vector<std::string> Cheat::GameArrays::EmergencyModels = {
	"AMBULANCE", "FBI", "FBI2", "FIRETRUK", "LGUARD",
	"PBUS", "PRANGER", "POLICE", "POLICE2", "POLICE3",
	"POLICE4", "POLICEB", "POLICEOLD1", "POLICEOLD2", "POLICET",
	"SHERIFF", "SHERIFF2", "RIOT"
};
const std::vector<std::string> Cheat::GameArrays::HelicopterModels = {
	"ANNIHILATOR", "BLIMP", "BLIMP2", "BUZZARD", "BUZZARD2",
	"CARGOBOB", "CARGOBOB2", "CARGOBOB3", "CARGOBOB4", "FROGGER",
	"FROGGER2", "MAVERICK", "POLMAV", "SAVAGE", "SKYLIFT",
	"SUPERVOLITO", "SUPERVOLITO2", "SWIFT", "SWIFT2", "VALKYRIE",
	"VALKYRIE2", "VOLATUS"
};
const std::vector<std::string> Cheat::GameArrays::IndustrialModels = {
	"BULLDOZER", "CUTTER", "DUMP", "FLATBED", "GUARDIAN",
	"HANDLER", "MIXER", "MIXER2", "RUBBLE", "TIPTRUCK",
	"TIPTRUCK2"
};
const std::vector<std::string> Cheat::GameArrays::MilitaryModels = {
	"BARRACKS", "BARRACKS2", "BARRACKS3", "CRUSADER", "RHINO"
};
const std::vector<std::string> Cheat::GameArrays::MotorcycleModels = {
	"AKUMA", "AVARUS", "BAGGER", "BATI", "BATI2",
	"BF400", "CARBONRS", "CHIMERA", "CLIFFHANGER", "DAEMON",
	"DAEMON2", "DEFILER", "DOUBLE", "ENDURO", "ESSKEY",
	"FAGGIO", "FAGGIO2", "FAGGIO3", "GARGOYLE", "HAKUCHOU",
	"HAKUCHOU2", "HEXER", "INNOVATION", "LECTRO", "MANCHEZ",
	"NEMESIS", "NIGHTBLADE", "PCJ", "RATBIKE", "RUFFIAN",
	"SANCHEZ", "SANCHEZ2", "SANCTUS", "SHOTARO", "SOVEREIGN",
	"THRUST", "VADER", "VINDICATOR", "VORTEX", "WOLFSBANE",
	"ZOMBIEA", "ZOMBIEB", "DIABLOUS", "DIABLOUS2", "FCR",
	"FCR2"
};
const std::vector<std::string> Cheat::GameArrays::MuscleModels = {
	"BLADE", "BUCCANEER", "BUCCANEER2", "CHINO", "CHINO2",
	"COQUETTE3", "DOMINATOR", "DOMINATOR2", "DUKES", "DUKES2",
	"GAUNTLET", "GAUNTLET2", "FACTION", "FACTION2", "FACTION3",
	"HOTKNIFE", "LURCHER", "MOONBEAM", "MOONBEAM2", "NIGHTSHADE",
	"PHOENIX", "PICADOR", "RATLOADER", "RATLOADER2", "RUINER", "RUINER2", "RUINER3",
	"SABREGT", "SABREGT2", "SLAMVAN", "SLAMVAN2", "SLAMVAN3",
	"STALION", "STALION2", "TAMPA", "VIGERO", "VIRGO",
	"VIRGO2", "VIRGO3", "VOODOO", "VOODOO2"
};
const std::vector<std::string> Cheat::GameArrays::OffRoadModels = {
	"BFINJECTION", "BIFTA", "BLAZER", "BLAZER2", "BLAZER3",
	"BLAZER4", "BODHI2", "BRAWLER", "DLOADER", "DUBSTA3",
	"DUNE", "DUNE2", "INSURGENT", "INSURGENT2", "KALAHARI",
	"MARSHALL", "MESA3", "MONSTER", "RANCHERXL", "RANCHERXL2",
	"REBEL", "REBEL2", "SANDKING", "SANDKING2", "TECHNICAL",
	"TROPHYTRUCK", "TROPHYTRUCK2", "TECHNICAL2", "DUNE4", "DUNE5",
	"BLAZER5"
};
const std::vector<std::string> Cheat::GameArrays::PlaneModels = {
	"BESRA", "CARGOPLANE", "CUBAN800", "DODO", "DUSTER",
	"HYDRA", "JET", "LAZER", "LUXOR", "LUXOR2",
	"MAMMATUS", "MILJET", "NIMBUS", "SHAMAL", "STUNT",
	"TITAN", "VELUM", "VELUM2", "VESTRA"
};
const std::vector<std::string> Cheat::GameArrays::SedanModels = {
	"ASEA", "ASEA2", "ASTEROPE", "COG55", "COG552",
	"COGNOSCENTI", "COGNOSCENTI2", "EMPEROR", "EMPEROR2", "EMPEROR3",
	"FUGITIVE", "GLENDALE", "INGOT", "INTRUDER", "LIMO2",
	"PREMIER", "PRIMO", "PRIMO2", "REGINA", "ROMERO",
	"SCHAFTER2", "SCHAFTER5", "SCHAFTER6", "STANIER", "STRATUM",
	"STRETCH", "SUPERD", "SURGE", "TAILGATER", "WARRENER",
	"WASHINGTON"
};
const std::vector<std::string> Cheat::GameArrays::ServiceModels = {
	"AIRBUS", "BRICKADE", "BUS", "COACH", "RALLYTRUCK",
	"RENTALBUS", "TAXI", "TOURBUS", "TRASH", "TRASH2",
	"WASTELANDER",
};
const std::vector<std::string> Cheat::GameArrays::SportModels = {
	"ALPHA", "BANSHEE", "BESTIAGTS", "BLISTA2", "BLISTA3",
	"BUFFALO", "BUFFALO2", "BUFFALO3", "CARBONIZZARE", "COMET2",
	"COQUETTE", "ELEGY", "ELEGY2", "FELTZER2", "FUROREGT", "FUSILADE",
	"FUTO", "JESTER", "JESTER2", "KHAMELION", "KURUMA",
	"KURUMA2", "LYNX", "MASSACRO", "MASSACRO2", "NINEF",
	"NINEF2", "OMNIS", "PENUMBRA", "RAPIDGT", "RAPIDGT2",
	"RAPTOR", "SCHAFTER3", "SCHAFTER4", "SCHWARTZER", "SEVEN70",
	"SULTAN", "SURANO", "SPECTER", "SPECTER2", "TAMPA2", "TROPOS", "VERLIERER2",
	"RUINER2", "PHANTOM2", "RUSTON"
};
const std::vector<std::string> Cheat::GameArrays::SportClassicModels = {
	"BTYPE", "BTYPE2", "BTYPE3", "CASCO", "COQUETTE2",
	"FELTZER3", "JB700", "MAMBA", "MANANA", "MONROE",
	"PEYOTE", "PIGALLE", "STINGER", "STINGERGT", "TORNADO",
	"TORNADO2", "TORNADO3", "TORNADO4", "TORNADO5", "TORNADO6",
	"ZTYPE", "INFERNUS2", "TURISMO2",
};
const std::vector<std::string> Cheat::GameArrays::SuperModels = {
	"ADDER", "BANSHEE2", "BULLET", "CHEETAH", "ENTITYXF",
	"FMJ", "SHEAVA", "INFERNUS", "NERO", "NERO2","OSIRIS", "LE7B",
	"ITALIGTB", "ITALIGTB2", "PFISTER811", "PROTOTIPO", "REAPER", "SULTANRS", "T20",
	"TEMPESTA", "TURISMOR", "TYRUS", "VACCA", "VOLTIC", "ZENTORNO", "VOLTIC2", "PENETRATOR", "GP1"
};
const std::vector<std::string> Cheat::GameArrays::SUVModels = {
	"BALLER", "BALLER2", "BALLER3", "BALLER4", "BALLER5",
	"BALLER6", "BJXL", "CAVALCADE", "CAVALCADE2", "CONTENDER",
	"DUBSTA", "DUBSTA2", "FQ2", "GRANGER", "GRESLEY",
	"HABANERO", "HUNTLEY", "LANDSTALKER", "MESA", "MESA2",
	"PATRIOT", "RADI", "ROCOTO", "SEMINOLE", "SERRANO",
	"XLS", "XLS2"
};
const std::vector<std::string> Cheat::GameArrays::TrailerModels = {
	"ARMYTANKER", "ARMYTRAILER", "ARMYTRAILER2", "BALETRAILER", "BOATTRAILER",
	"DOCKTRAILER", "FREIGHTTRAILER", "GRAINTRAILER", "PROPTRAILER", "RAKETRAILER",
	"TANKER", "TANKER2", "TR2", "TR3", "TR4",
	"TRAILERLOGS", "TRAILERS", "TRAILERS2", "TRAILERS3", "TRAILERSMALL",
	"TRFLAT", "TVTRAILER"
};
const std::vector<std::string> Cheat::GameArrays::TrainModels = {
	"CABLECAR", "FREIGHT", "FREIGHTCAR", "FREIGHTCONT1", "FREIGHTCONT2",
	"FREIGHTGRAIN", "METROTRAIN", "TANKERCAR"
};
const std::vector<std::string> Cheat::GameArrays::UtilityModels = {
	"AIRTUG", "CADDY", "CADDY2", "DOCKTUG", "FORKLIFT",
	"MOWER", "RIPLEY", "SADLER", "SADLER2", "SCRAP",
	"TOWTRUCK", "TOWTRUCK2", "TRACTOR", "TRACTOR2", "TRACTOR3",
	"UTILLITRUCK", "UTILLITRUCK2", "UTILLITRUCK3"
};
const std::vector<std::string> Cheat::GameArrays::VanModels = {
	"BISON", "BISON2", "BISON3", "BOBCATXL", "BOXVILLE",
	"BOXVILLE2", "BOXVILLE3", "BOXVILLE4", "BURRITO", "BURRITO2",
	"BURRITO3", "BURRITO4", "BURRITO5", "CAMPER", "GBURRITO",
	"GBURRITO2", "JOURNEY", "MINIVAN", "MINIVAN2", "PARADISE",
	"PONY", "PONY2", "RUMPO", "RUMPO2", "RUMPO3",
	"SPEEDO", "SPEEDO2", "SURFER", "SURFER2", "TACO",
	"YOUGA", "YOUGA2"
};
const std::vector<std::string> Cheat::GameArrays::SSASSSModels = {
	"caracara", "cheburek", "dominator3", "ellie", "entity2",
	"fagaloa", "flashgt", "gb200", "hotring", "issi3",
	"michelli", "seasparrow", "tezeract", "taipan",
	"tyrant"
};
const std::vector<std::string> Cheat::GameArrays::DoomsdayModels = {
	"AUTARCH", "AVENGER", "BARRAGE", "CHERNOBOG", "COMET4", "COMET5",
	"DELUXO", "GT500", "HERMES", "HUSTLER", "KAMACHO","KHANJALI",
	"NEON", "PARIAH", "RAIDEN", "REVOLTER", "RIATA", "RIOT2", "SAVESTRA",
	"SC1", "SENTINEL3", "STREITER", "STROMBERG", "THRUSTER", "VISERIS",
	"VOLATOL", "YOSEMITE", "Z190"
};
const std::vector<std::string> Cheat::GameArrays::GunrunningModels = {
	"HAULER2",		"PHANTOM3",		"APC",
	"HALFTRACK",	"TRAILERSMALL12",	"OPPRESSOR",
	"TAMPA3",		"DUNE3",			"INSURGENT3",
	"NIGHTSHARK",	"TECHNICAL3",		"ARDENT",
	"CHEETAH2",	"TORERO",			"VAGNER",
	"XA21",		"CADDY3",			"TRAILERLARGE",
	"TRAILERS4"
};
const std::vector<std::string> Cheat::GameArrays::AfterHoursModels = {
	"BLIMP3",		"MENACER",		"MULE4",
	"PATRIOT2",	"POUNDER2",	"STRIKEFORCE",
	"SCRAMJET",	"SPEEDO4",		"STAFFORD",
	"SWINGER",		"TERBYTE",		"OPPRESSOR2",
	"scramjet",	"JESTER3"
};
const std::vector<std::string> Cheat::GameArrays::ArenaWarModels = {
	"BRUISER",		"BRUISER2",	"BRUISER3",
	"BRUTUS",		"BRUTUS2",		"BRUTUS3",
	"CERBERUS",	"CERBERUS2",	"CERBERUS3",
	"CLIQUE",		"DEATHBIKE",	"DEATHBIKE2",
	"DEATHBIKE3",	"DEVESTE",		"DEVIANT",
	"DOMINATOR4",	"DOMINATOR5",	"DOMINATOR6",
	"IMPALER",		"IMPALER2",	"IMPALER3",
	"IMPALER4",	"IMPERATOR",	"IMPERATOR2",
	"IMPERATOR3",	"ISSI4",		"SLAMVAN5",
	"ISSI5",		"ISSI6",		"ITALIGTO",
	"MONSTER3",	"MONSTER4",	"MONSTER5",
	"RCBANDITO",	"SCARAB2",		"SCARAB3",
	"SCHLAGEN",	"SLAMVAN4",	"SLAMVAN6",
	"TOROS",		"TULIP",		"VAMOS",
	"ZR380",		"ZR3802",		"ZR3803"
};

const std::vector<std::string> Cheat::GameArrays::CasinoDLCModels = {
	"CARACARA2",	"DRAFTER",		"DYNASTY",
	"EMERUS",		"GAUNTLET3",	"GAUNTLET4",
	"HELLION",		"ISSI7",		"JUGULAR",
	"KRIEGER",		"LOCUST",		"NEBULA",
	"NEO",			"NOVAK",		"PARAGON",
	"PARAGON2",    "PEYOTE2",		"THRAX",
	"RROCKET",		"S80",		"ZION3",
	"zorrusso"
};

const std::vector<std::string> Cheat::GameArrays::DiamondCasinoHeistDLCModels = {
	"ASBO",		"EVERON",	"FORMULA",
	"FORMULA2",	"FURIA",   "IMORGON",
	"JB7002",		"KANJO",	"KOMODA",
	"MINITANK",	"OUTLAW",	"REBLA",
	"RETINUE2",	"STRYDER", "SUGOI",
	"SULTAN2",		"VAGRANT", "VSTR",
	"YOSEMITE2",   "ZHABA"
};

const std::vector<std::string> Cheat::GameArrays::CunningStuntsDLCModels = {
	"GP1", "TURISMO2", "INFERNUS2", "RUSTON"
};

const std::vector<std::string> Cheat::GameArrays::SmugglersRunModels = {
	"ALPHAZ1",		"BOMBUSHKA", "CYCLONE",
	"HAVOK",		"HOWARD",	  "HUNTER",
	"MICROLIGHT",  "MOGUL",	  "MOLOTOK",
	"NOKOTA",		"PYRO",	  "RAPIDGT3",
	"RETINUE",     "ROGUE",     "SEABREEZE",
	"STARLING",    "TULA",      "VIGILANTE",
	"VISIONE"
};

const std::vector<std::string> Cheat::GameArrays::SummerSpecialModels = {
	"PENUMBRA2",		"OPENWHEEL2",	"OPENWHEEL1",
	"PEYOTE3",			"SEMINOLE2",   "TIGON",
	"YOSEMITE3",		"YOUGA3",		"MANANA2",
	"LANDSTALKER2",	"GLENDALE2",	"GAUNTLET5",
	"DUKES3",			"COQUETTE4",	"CLUB"
};

const std::vector<std::string> Cheat::GameArrays::CayoPericoHeistModels = {
	"ALKONOST",	"ANNIHILATOR2", "AVISA",
	"BRIOSO2", "DINGHY5", "ITALIRSX", "VETO2",
	"PENUMBRA2", "OPENWHEEL2", "KOSATKA",
	"LONGFIN", "MANCHEZ2",  "PATROLBOAT",
	"SEASPARROW2", "seasparrow3", "SQUADDIE",
	"SLAMTRUCK", "TOREADOR", "VERUS",
	"VETIR", "WINKY","WEEVIL", "VETO"
};

const std::vector<std::string> Cheat::GameArrays::LosSantosTunersModels = {
	"CALICO", "COMET6", "CYPHER", "DOMINATOR7", "DOMINATOR8", "EUROS", "FREIGHTCAR2",
	"FUTO2", "GROWLER", "JESTER4","PREVION", "REMUS", "RT3000","SULTAN3", "TAILGATER2", "VECTRE",
	"WARRENER", "WARRENER2", "ZR350"
};

const std::vector<std::string> Cheat::GameArrays::TheContractModels = {
	"BUFFALO4", "GRANGER2", "IWAGEN","PATRIOT3", "ASTRON", "DEITY", "IGNUS",
	"JUBILEE", "REEVER", "SHINOBI", "SUGOI", "ZENO", "BALLER7", "CHAMPION", "CINQUEMILA", "COMET7"
};

const std::vector<std::string> Cheat::GameArrays::TheCriminalEnterprisesDLC = {
	"TENF",	"WEEVIL2",	"TORERO2", "SENTINEL4","POSTLUDE","DRAUGUR",
	"RHINEHART","VIGERO2","GREENWOOD", "OMNISEGT",	"RUINER4","CORSITA",
	"LM87",	"SM722", "CONADA"
};

const std::vector<VehicleModelPicturesStruct> Cheat::GameArrays::VehicleModelPictures = {
{"candc_heist4","alkonost"},
{"candc_heist4","annihilator2"},
{"candc_heist4","avisa"},
{"sssa_dlc_heist4","brioso2"},
{"candc_heist4","dinghy5"},
{"lgm_dlc_heist4","italirsx"},
{"sssa_dlc_heist4","kosatka"},
{"dock_dlc_heist4","longfin"},
{"candc_heist4","manchez2"},
{"candc_heist4","patrolboat"},
{"sssa_dlc_heist4","seasparrow2"},
{"candc_heist4","seasparrow3"},
{"sssa_dlc_heist4","slamtruck"},
{"candc_heist4","squaddie"},
{"candc_heist4","toreador"},
{"candc_heist4","verus"},
{"candc_heist4","vetir"},
{"candc_heist4","veto"},
{"candc_heist4","veto2"},
{"candc_heist4","weevil"},
{"candc_heist4","winky"},
{"lgm_dlc_executive1","pfister811"},
{"lgm_default","adder"},
{"lgm_dlc_xmas2017","autarch_b"},
{"lsc_jan2016","banshee2"},
{"lgm_default","bullet"},
{"lgm_default","cheetah"},
{"lgm_dlc_smuggler","cyclone"},
{"lgm_dlc_smuggler","cyclone"},
{"lgm_dlc_arena","deveste"},
{"lgm_dlc_stunt","sheava"},
{"lgm_dlc_vinewood","emerus"},
{"lgm_dlc_assault","entity2"},
{"lgm_default","entityxf"},
{"lgm_dlc_executive1","fmj"},
{"lgm_dlc_casinoheist","furia"},
{"lgm_dlc_specialraces","gp1"},
{"sssa_default","infernus"},
{"lsc_dlc_import_export","italigtb2"},
{"lsc_dlc_import_export","italigtb"},
{"lgm_dlc_vinewood","krieger"},
{"lsc_dlc_import_export","nero2_b"},
{"lsc_dlc_import_export","nero2_a"},
{"lgm_dlc_luxe","Osiris"},
{"lgm_dlc_importexport","penetrator"},
{"lgm_dlc_stunt","le7b"},
{"lgm_dlc_executive1","reaper"},
{"candc_importexport","voltic2"},
{"lgm_dlc_vinewood","s80"},
{"lgm_dlc_xmas2017","sc1_b"},
{"candc_battle","scramjet"},
{"lsc_jan2016","sultan2_a"},
{"lgm_dlc_luxe","t20"},
{"lgm_dlc_assault","taipan"},
{"lgm_dlc_importexport","tempesta"},
{"lgm_dlc_assault","tezeract"},
{"lgm_dlc_vinewood","thrax"},
{"lgm_dlc_business","turismor"},
{"lgm_dlc_assault","tyrant"},
{"lgm_dlc_stunt","tyrus"},
{"lgm_default","vacca"},
{"lgm_dlc_gunrunning","vagner"},
{"candc_smuggler","vigilante"},
{"lgm_dlc_smuggler","visione"},
{"lgm_default","voltic_tless"},
{"lgm_dlc_executive1","prototipo"},
{"lgm_dlc_gunrunning","xa21"},
{"lgm_dlc_business2","zentorno"},
{"lgm_dlc_vinewood","zorrusso"},
{"lgm_dlc_business","alpha"},
{"lgm_dlc_business2","banshee_tless"},
{"sssa_dlc_mp_to_sp","blista2"},
{"lgm_dlc_executive1","bestiagts"},
{"sssa_dlc_hipster","buffalo"},
{"sssa_dlc_mp_to_sp","buffalo3"},
{"sssa_dlc_hipster","buffalo"},
{"lgm_default","carboniz"},
{"lsc_dlc_import_export","comet3"},
{"sssa_default","comet2"},
{"lgm_dlc_xmas2017","comet4_b"},
{"lgm_dlc_xmas2017","comet5_b"},
{"lgm_default","coquette"},
{"lgm_dlc_vinewood","drafter"},
{"sssa_dlc_stunt","tampa2"},
{"lgm_default","elegy2"},
{"lsc_dlc_import_export","elegy"},
{"lgm_dlc_casinoheist", "formula"},
{"lgm_dlc_casinoheist", "formula2"},
{"lgm_dlc_assault","flashgt"},
{"lgm_dlc_lts_creator","furore"},
{"sssa_dlc_business2","fusilade"},
{"sssa_dlc_battle","futo"},
{"lgm_dlc_assault","gb200"},
{"sssa_dlc_assault","hotring"},
{"lgm_dlc_casinoheist","imorgon"},
{"sssa_dlc_vinewood","issi7"},
{"lgm_dlc_arena","italigto"},
{"sssa_dlc_christmas_2","jester2"},
{"lgm_dlc_assault","jester3"},
{"lgm_dlc_business","jester"},
{"lgm_dlc_vinewood","jugular"},
{"lgm_dlc_casinoheist","komoda"},
{"sssa_dlc_heist","kuruma2"},
{"sssa_dlc_heist","kuruma"},
{"lgm_dlc_vinewood","locust"},
{"lgm_dlc_stunt","lynx"},
{"sssa_dlc_christmas_2","massacro2"},
{"lgm_dlc_business2","massacro"},
{"lgm_dlc_vinewood","neo"},
{"lgm_dlc_xmas2017","neon_b"},
{"lgm_default","ninef2"},
{"sssa_default","ninef"},
{"sssa_dlc_stunt","omnis"},
{"lgm_dlc_vinewood","paragon"},
{"lgm_dlc_vinewood","paragon"},
{"lgm_dlc_xmas2017","pariah_b"},
{"sssa_dlc_business2","penumbra"},
{"lgm_dlc_xmas2017","raiden_b"},
{"lgm_default","rapidgt2"},
{"lgm_default","rapidgt"},
{"lgm_dlc_biker","raptor"},
{"lgm_dlc_xmas2017","revolter_b"},
{"lgm_dlc_specialraces","ruston"},
{"lgm_dlc_apartments","schafter4"},
{"lgm_dlc_apartments","schafter3"},
{"lgm_dlc_arena","schlagen"},
{"sssa_default","schwarze"},
{"sssa_dlc_xmas2017","sentinel3_b"},
{"lgm_dlc_executive1","seven70"},
{"lsc_dlc_import_export","specter2_a"},
{"lsc_dlc_import_export","specter2_b"},
{"lgm_dlc_xmas2017","streiter_b"},
{"sssa_dlc_casinoheist","sugoi"},
{"lsc_jan2016","sultan2_a"},
{"sssa_dlc_casinoheist","sultan2"},
{"lgm_default","surano_convertable"},
{"sssa_dlc_stunt","tropos"},
{"lgm_dlc_casinoheist","vstr"},
{"lgm_dlc_apartments","verlier"},
{"mba_vehicles","zr3802"},
{"mba_vehicles","zr3803"},
{"mba_vehicles","zr3801"},
{"candc_gunrunning","ardent"},
{"lgm_dlc_heist","casco"},
{"sssa_dlc_assault","cheburek"},
{"lgm_dlc_gunrunning","cheetah2"},
{"lgm_dlc_pilot","coquette2"},
{"candc_xmas2017","deluxo_b"},
{"sssa_dlc_vinewood","dynasty"},
{"sssa_dlc_assault","fagaloa"},
{"lgm_dlc_xmas2017","gt500_b"},
{"lgm_dlc_specialraces","infernus2"},
{"lgm_default","jb700"},
{"lgm_dlc_apartments","mamba"},
{"sssa_dlc_assault","michelli"},
{"lgm_default","monroe"},
{"sssa_dlc_vinewood","nebula"},
{"sssa_dlc_hipster","pigalle"},
{"lgm_dlc_smuggler","rapidgt3"},
{"sssa_dlc_casinoheist","retinue2"},
{"sssa_dlc_smuggler","retinue_b"},
{"sssa_dlc_halloween","btype2"},
{"lgm_dlc_valentines2","roosevelt2"},
{"lgm_dlc_valentines","roosevelt"},
{"lgm_dlc_xmas2017","savestra_b"},
{"lgm_default","stingerg"},
{"lgm_default","stinger"},
{"lgm_dlc_luxe","feltzer3"},
{"candc_xmas2017","stromberg_b"},
{"lgm_dlc_battle","swinger"},
{"lgm_dlc_gunrunning","torero"},
{"lsc_lowrider2","tornado5_a"},
{"sssa_dlc_biker","tornado6"},
{"lgm_dlc_specialraces","turismo2"},
{"lgm_dlc_xmas2017","viseris_b"},
{"lgm_default","ztype"},
{"lgm_dlc_xmas2017","z190_b"},
{"sssa_dlc_vinewood","zion3"},
{"lgm_default","cogcabri"},
{"sssa_default","exemplar"},
{"sssa_dlc_business2","f620"},
{"sssa_default","felon"},
{"sssa_default","felon2"},
{"sssa_dlc_heist","jackal"},
{"sssa_default","oracle"},
{"sssa_dlc_heist","oracle1"},
{"sssa_dlc_business2","sentinel"},
{"sssa_dlc_business2","sentinel"},
{"lgm_dlc_luxe","windsor"},
{"sssa_default","zion"},
{"sssa_default","zion2"},
{"sssa_dlc_hipster","blade"},
{"lsc_default","buccaneer2_b"},
{"lsc_default","buccaneer2_a"},
{"lsc_default","chino2_a"},
{"lgm_dlc_luxe","chino"},
{"lgm_dlc_arena","clique"},
{"lgm_dlc_luxe","coquette3"},
{"lgm_dlc_arena","deviant"},
{"sssa_dlc_assault","dominator3"},
{"mba_vehicles","dominato_c_1"},
{"mba_vehicles","dominato_c_2"},
{"mba_vehicles","dominato_c_3"},
{"sssa_dlc_business2","dominato"},
{"candc_default","dukes"},
{"sssa_dlc_mp_to_sp","dukes"},
{"sssa_dlc_assault","ellie"},
{"lsc_lowrider2","faction3_b"},
{"lsc_lowrider2","faction3_a"},
{"lsc_default","faction2_a"},
{"sssa_dlc_mp_to_sp","gauntlet2"},
{"sssa_dlc_vinewood","gauntlet3"},
{"sssa_dlc_vinewood","gauntlet4"},
{"sssa_default","gauntlet"},
{"sssa_dlc_xmas2017","hermes_b"},
{"lgm_default","hotknife"},
{"lgm_dlc_xmas2017","hustler_b"},
{"mba_vehicles","impaler"},
{"sssa_dlc_vinewood","impaler"},
{"mba_vehicles","impaler_c_1"},
{"mba_vehicles","impaler_c_2"},
{"mba_vehicles","impaler_c_3"},
{"mba_vehicles","imperator2"},
{"mba_vehicles","imperator3"},
{"mba_vehicles","imperator1"},
{"sssa_dlc_halloween","lurcher"},
{"lsc_default","moonbeam2"},
{"lgm_dlc_apartments","niteshad"},
{"sssa_dlc_vinewood","peyote2"},
{"sssa_dlc_hipster","picador"},
{"sssa_dlc_mp_to_sp","dominator2"},
{"sssa_dlc_valentines","rloader"},
{"sssa_dlc_christmas_2","rloader2"},
{"candc_importexport","ruiner2"},
{"sssa_dlc_battle","ruiner"},
{"lsc_lowrider2","sabregt2_a"},
{"lsc_lowrider2","slamvan3_b"},
{"mba_vehicles","slamvan_c_1"},
{"mba_vehicles","slamvan_c_2"},
{"mba_vehicles","slamvan_c_3"},
{"sssa_dlc_christmas_2","slamvan"},
{"sssa_dlc_mp_to_sp","stalion2"},
{"sssa_dlc_mp_to_sp","stallion"},
{"candc_gunrunning","tampa3"},
{"sssa_dlc_christmas_3","tampa"},
{"sssa_dlc_arena","tulip"},
{"sssa_dlc_arena","vamos"},
{"sssa_default","vigero"},
{"lsc_lowrider2","virgo2_a"},
{"lsc_lowrider2","virgo2_b"},
{"lgm_dlc_luxe","virgo"},
{"lsc_default","voodoo_b"},
{"lsc_default","voodoo_a"},
{"sssa_dlc_xmas2017","yosemite_b"},
{"sssa_dlc_casinoheist","yosemite2"},
{"sssa_default","bfinject"},
{"sssa_default","bifta"},
{"sssa_dlc_hipster","blazer3"},
{"candc_importexport","blazer5"},
{"sssa_default","blazer"},
{"sssa_dlc_biker","blazer4"},
{"sssa_default","bodhi2"},
{"lgm_dlc_luxe","brawler"},
{"mba_vehicles","bruiser_c_2"},
{"mba_vehicles","bruiser_c_3"},
{"mba_vehicles","bruiser_c_1"},
{"mba_vehicles","brutus2"},
{"mba_vehicles","brutus3"},
{"mba_vehicles","brutus1"},
{"sssa_dlc_vinewood","caracara2"},
{"candc_assault","caracara"},
{"candc_default","dubsta3"},
{"candc_gunrunning","dune3"},
{"sssa_default","dune"},
{"sssa_dlc_casinoheist","everon"},
{"lgm_dlc_battle","freecrawler"},
{"sssa_dlc_vinewood","hellion"},
{"ua_generic","ua_unlock_11"},
{"candc_default","insurgent"},
{"candc_default","insurgent"},
{"sssa_default","kalahari"},
{"sssa_dlc_xmas2017","kamacho_b"},
{"candc_default","marshall"},
{"candc_battle","menacer"},
{"candc_default","mesa3"},
{"mba_vehicles","monster_c_1"},
{"mba_vehicles","monster_c_2"},
{"mba_vehicles","monster_c_3"},
{"candc_gunrunning","nightshark"},
{"sssa_dlc_casinoheist","outlaw"},
{"candc_importexport","dune5"},
{"sssa_dlc_business","rancherx"},
{"sssa_dlc_arena","rcbandito"},
{"sssa_dlc_hipster","rebel2"},
{"sssa_default","rebel"},
{"sssa_dlc_xmas2017","riata_b"},
{"sssa_default","sandking_b"},
{"sssa_default","sandkin_2b"},
{"candc_importexport","technical2"},
{"ua_generic","ua_unlock_15"},
{"candc_default","technical"},
{"candc_default","monster"},
{"sssa_dlc_stunt","trophy2"},
{"sssa_dlc_stunt","trophy"},
{"sssa_dlc_casinoheist","vagrant"},
{"sssa_default","akuma"},
{"sssa_dlc_biker","avarus"},
{"sssa_dlc_stunt","bf400"},
{"sssa_dlc_biker","bagger"},
{"sssa_default","bati2"},
{"sssa_default","bati"},
{"lgm_default","carbon"},
{"sssa_dlc_biker","chimera"},
{"sssa_dlc_stunt","cliffhanger"},
{"sssa_dlc_biker","daemon2"},
{"mba_vehicles","deathbike_c_2"},
{"mba_vehicles","deathbike_c_3"},
{"mba_vehicles","deathbike_c_1"},
{"sssa_dlc_biker","defiler"},
{"lsc_dlc_import_export","diablous2"},
{"sssa_default","double"},
{"sssa_dlc_heist","enduro"},
{"sssa_dlc_biker","esskey"},
{"lsc_dlc_import_export","fcr2_b"},
{"lsc_dlc_import_export","fcr2_a"},
{"sssa_dlc_biker","faggio3"},
{"sssa_default","faggio"},
{"sssa_dlc_biker","faggion"},
{"sssa_dlc_stunt","gargoyle"},
{"lgm_dlc_biker","hakuchou2"},
{"sssa_dlc_lts_creator","hakuchou"},
{"sssa_default","hexer"},
{"sssa_dlc_lts_creator","innovation"},
{"lgm_dlc_heist","lectro"},
{"sssa_dlc_biker","manchez"},
{"sssa_dlc_heist","nemesis"},
{"sssa_dlc_biker","nightblade"},
{"candc_battle","oppressor2"},
{"candc_gunrunning","oppressor"},
{"sssa_default","pcj"},
{"sssa_dlc_biker","ratbike"},
{"lgm_dlc_vinewood","rrocket"},
{"sssa_default","ruffian"},
{"sssa_default","sanchez2"},
{"sssa_default","sanchez"},
{"sssa_dlc_biker","sanctus"},
{"lgm_dlc_biker","shotaro"},
{"lgm_dlc_casinoheist","stryder"},
{"lgm_dlc_business2","thrust"},
{"sssa_default","vader"},
{"lgm_dlc_luxe","vindicator"},
{"sssa_dlc_biker","vortex"},
{"sssa_dlc_biker","wolfsbane"},
{"sssa_dlc_biker","zombieb"},
{"sssa_dlc_biker","zombiea"},
{"candc_gunrunning","apc"},
{"candc_gunrunning","trsmall2"},
{"candc_default","barracks"},
{"candc_xmas2017","barrage_b"},
{"candc_xmas2017","chernobog_b"},
{"candc_default","crusader"},
{"candc_gunrunning","halftrack"},
{"candc_xmas2017","khanjali_b"},
{"candc_default","rhino"},
{"mba_vehicles","scarab2"},
{"mba_vehicles","scarab3"},
{"mba_vehicles","scarab1"},
{"candc_xmas2017","thruster_b"},
{"candc_default","pbus"},
{"candc_xmas2017","riot2_b"},
{"candc_default","airbus"},
{"candc_executive1","brickade"},
{"candc_default","bus"},
{"candc_default","coach"},
{"sssa_dlc_stunt","rallytruck"},
{"sssa_dlc_battle","pbus2"},
{"candc_default","rentbus"},
{"candc_importexport","wastlndr"},
{"sssa_dlc_business","asea"},
{"sssa_dlc_business","astrope"},
{"lgm_dlc_apartments","cognosc"},
{"sssa_dlc_business","premier"},
{"sssa_default","superd"},
{"sssa_default","fugitive"},
{"sssa_dlc_hipster","glendale"},
{"sssa_dlc_business","intruder"},
{"sssa_default","stretch"},
{"sssa_dlc_hipster","primo"},
{"sssa_dlc_hipster","regina"},
{"sssa_dlc_battle","Romero"},
{"lgm_dlc_apartments","schafter3"},
{"lgm_dlc_apartments","schafter4"},
{"sssa_dlc_heist","schafter2"},
{"lgm_dlc_battle","stafford"},
{"sssa_dlc_business","stanier"},
{"sssa_dlc_business","stratum"},
{"sssa_dlc_heist","surge"},
{"sssa_dlc_hipster","tailgater"},
{"sssa_dlc_business","ingot"},
{"sssa_dlc_hipster","warrener"},
{"sssa_dlc_business","washingt"},
{"candc_default","dump"},
{"sssa_dlc_heist","guardian"},
{"sssa_dlc_casinoheist","asbo"},
{"sssa_default","dilettan"},
{"sssa_dlc_stunt","brioso"},
{"sssa_dlc_assault","issi3"},
{"mba_vehicles","issi3_c_1"},
{"mba_vehicles","issi3_c_2"},
{"mba_vehicles","issi3_c_3"},
{"sssa_dlc_casinoheist","kanjo"},
{"sssa_dlc_hipster","panto"},
{"sssa_dlc_battle","prairie"},
{"sssa_dlc_hipster","rhapsody"},
{"sssa_default","issi2"},
{"mba_vehicles","cerberus2"},
{"mba_vehicles","cerberus3"},
{"mba_vehicles","cerberus1"},
{"candc_truck","cab_1"},
{"candc_default","mule3"},
{"candc_battle","mule4"},
{"candc_default","mule"},
{"candc_truck","cab_0"},
{"candc_importexport","phantom2"},
{"candc_battle","pounder2"},
{"elt_dlc_smuggler","alphaz1"},
{"candc_chopper","banner_5"},
{"candc_chopper","banner_4"},
{"elt_dlc_pilot","besra"},
{"elt_dlc_battle","blimp3"},
{"candc_smuggler","bombushka"},
{"elt_default","cuban800"},
{"elt_default","dodo"},
{"elt_default","duster"},
{"elt_dlc_smuggler","howard"},
{"candc_default","hydra"},
{"elt_dlc_executive1","luxor2"},
{"elt_default","luxor"},
{"elt_default","mammatus"},
{"elt_dlc_smuggler","microlight"},
{"elt_dlc_pilot","miljet"},
{"candc_smuggler","mogu"},
{"candc_smuggler","molotok_b"},
{"elt_dlc_executive1","nimbus"},
{"candc_smuggler","nokota"},
{"candc_smuggler","lazer"},
{"candc_smuggler","pyro"},
{"candc_smuggler","rogue"},
{"elt_dlc_smuggler","seabreeze"},
{"elt_default","shama"},
{"candc_smuggler","starling"},
{"candc_battle","strikeforce"},
{"elt_default","stunt"},
{"elt_default","titan"},
{"candc_smuggler","tula"},
{"elt_default","velum2"},
{"elt_default","velum"},
{"candc_xmas2017","volatol_b"},
{"foreclosures_bunker","transportation_2"},
{"foreclosures_bunker","transportation_1"},
{"candc_truck","banner_2"},
{"sssa_default","sadler"},
{"candc_xmas2017","akula_b"},
{"elt_default","annih"},
{"candc_default","buzzard"},
{"candc_default","cargobob"},
{"elt_default","frogger"},
{"elt_dlc_smuggler","havok"},
{"candc_smuggler","hunter"},
{"elt_default","maverick"},
{"candc_default","savage"},
{"elt_dlc_assault","sparrow"},
{"elt_dlc_executive1","swift2"},
{"elt_dlc_pilot","swift"},
{"candc_default","valkyrie"},
{"elt_dlc_executive1","volatus"},
{"sssa_dlc_hipster","surfer"},
{"sssa_default","bison"},
{"sssa_dlc_business","bobcatx"},
{"candc_importexport","boxville5"},
{"candc_default","boxville4"},
{"sssa_dlc_heist","gburrito2"},
{"candc_default","journey"},
{"lsc_lowrider2","minivan2_b"},
{"sssa_dlc_business","minivan"},
{"sssa_default","paradise"},
{"sssa_dlc_executive_1","rumpo3_b"},
{"sssa_dlc_heist","rumpo"},
{"sssa_dlc_biker","youga2"},
{"sssa_dlc_hipster","youga"},
{"dock_default","dinghy3"},
{"dock_default","jetmax"},
{"dock_default","marquis"},
{"dock_default","seashark"},
{"dock_default","squalo"},
{"dock_default","sub2"},
{"dock_default","suntrap"},
{"dock_default","toro"},
{"dock_default","tropic"},
{"pandm_default","bmx"},
{"pandm_default","cruiser"},
{"pandm_default","tribike2"},
{"pandm_default","scorcher"},
{"pandm_default","tribike3"},
{"pandm_default","tribike"},
{"sssa_default","baller2"},
{"lgm_dlc_apartments","baller4"},
{"lgm_dlc_apartments","baller3"},
{"sssa_dlc_battle","bjx"},
{"sssa_dlc_heist","seminole"},
{"sssa_dlc_business","cavcade2"},
{"sssa_default","cavcade"},
{"sssa_dlc_stunt","contender"},
{"sssa_dlc_battle","habanero"},
{"lgm_dlc_business2","huntley"},
{"sssa_dlc_battle","fq2"},
{"sssa_dlc_business","granger"},
{"sssa_dlc_heist","gresley"},
{"sssa_dlc_heist","landstalker"},
{"sssa_dlc_battle","patriot"},
{"candc_default","mesa"},
{"lgm_dlc_vinewood","novak"},
{"sssa_dlc_battle","patriot2"},
{"sssa_dlc_business","radi"},
{"lgm_dlc_casinoheist","rebla"},
{"sssa_default","rocoto"},
{"sssa_dlc_battle","serrano"},
{"lgm_dlc_arena","toros"},
{"lgm_dlc_executive1","xls"},
{"lgm_dlc_tuner","zr350" },
{"lgm_dlc_tuner","growler" },
{"lgm_dlc_tuner","cypher" },
{"lgm_dlc_tuner","comet6" },
{"lgm_dlc_tuner","jester4" },
{"lgm_dlc_tuner","tailgater2" },
{"lgm_dlc_tuner","vectre" },
{"lgm_dlc_tuner","euros" },
{"sssa_dlc_tuner","calico" },
{"sssa_dlc_tuner","dominator7" },
{"sssa_dlc_tuner","dominator8" },
{"sssa_dlc_tuner","futo2" },
{"sssa_dlc_tuner","previon" },
{"sssa_dlc_tuner","remus" },
{"sssa_dlc_tuner","rt3000" },
{"sssa_dlc_tuner","sultan3" },
{"sssa_dlc_tuner","warrener2" }
};

const std::vector<TeleportLocationStruct> Cheat::GameArrays::TeleportLocationsSafehouses = {
	{ "Michael's Safehouse", -827.138f, 176.368f, 70.4999f },
	{ "Franklin's Safehouse", -18.0355f, -1456.94f, 30.4548f },
	{ "Franklin's Safehouse 2", 10.8766f, 545.654f, 175.419f },
	{ "Trevor's Safehouse", 1982.13f, 3829.44f, 32.3662f },
	{ "Trevor's Safehouse 2", -1157.05f, -1512.73f, 4.2127f },
	{ "Trevor's Safehouse 3", 91.1407f, -1280.65f, 29.1353f },
	{ "Michael's Safehouse Inside", -813.603f, 179.474f, 72.1548f },
	{ "Franklin's Safehouse Inside", -14.3803f, -1438.51f, 31.1073f },
	{ "Franklin's Safehouse 2 Inside", 7.11903f, 536.615f, 176.028f },
	{ "Trevor's Safehouse Inside", 1972.61f, 3817.04f, 33.4278f },
	{ "Trevor's Safehouse 2 Inside", -1151.77f, -1518.14f, 10.6327f },
	{ "Trevor's Safehouse 3 Inside", 96.1536f, -1290.73f, 29.2664f }
};

const std::vector<TeleportLocationStruct> Cheat::GameArrays::TeleportLocationsHighAltitude = {
	{ "Airplane Graveyard Airplane Tail ", 2395.096f, 3049.616f, 60.053f },
	{ "FIB Building Roof", 150.126f, -754.591f, 262.865f },
	{ "Galileo Observatory Roof", -438.804f, 1076.097f, 352.411f },
	{ "IAA Building Roof", 134.085f, -637.859f, 262.851f },
	{ "Maze Bank Arena Roof", -324.300f, -1968.545f, 67.002f },
	{ "Maze Bank Roof", -75.015f, -818.215f, 326.176f },
	{ "Palmer-Taylor Power Station Chimney", 2732.931f, 1577.540f, 83.671f },
	{ "Rebel Radio", 736.153f, 2583.143f, 79.634f },
	{ "Sandy Shores Building Site Crane", 1051.209f, 2280.452f, 89.727f },
	{ "Satellite Dish Antenna", 2034.988f, 2953.105f, 74.602f },
	{ "Stab City", 126.975f, 3714.419f, 46.827f },
	{ "Very High Up", -129.964f, 8130.873f, 6705.307f },
	{ "Windmill Top", 2026.677f, 1842.684f, 133.313f }
};

const std::vector<TeleportLocationStruct> Cheat::GameArrays::TeleportLocationsUnderwater = {
	{ "Dead Sea Monster", -3373.726f, 504.714f, -24.656f },
	{ "Humane Labs Tunnel", 3619.749f, 2742.740f, 28.690f },
	{ "Sunken Body", -3161.078f, 3001.998f, -37.974f },
	{ "Sunken Cargo Ship", 3199.748f, -379.018f, -22.500f },
	{ "Sunken Plane", -942.350f, 6608.752f, -20.912f },
	{ "Underwater Hatch", 4273.950f, 2975.714f, -170.746f },
	{ "Underwater UFO", 762.426f, 7380.371f, -111.377f },
	{ "Underwater WW2 Tank", 4201.633f, 3643.821f, -39.016f }
};

const std::vector<TeleportLocationStruct> Cheat::GameArrays::TeleportLocationsLandmarks = {
	{ "Airport Entrance", -1034.6f, -2733.6f, 13.8f },
	{ "Airport Field", -1336.0f, -3044.0f, 13.9f },
	{ "Altruist Cult Camp", -1170.841f, 4926.646f, 224.295f },
	{ "Calafia Train Bridge", -517.869f, 4425.284f, 89.795f },
	{ "Cargo Ship", 899.678f, -2882.191f, 19.013f },
	{ "Chumash", -3192.6f, 1100.0f, 20.2f },
	{ "Chumash Historic Family Pier", -3426.683f, 967.738f, 8.347f },
	{ "Del Perro Pier", -1850.127f, -1231.751f, 13.017f },
	{ "Devin Weston's House", -2639.872f, 1866.812f, 160.135f },
	{ "El Burro Heights", 1384.0f, -2057.1f, 52.0f },
	{ "Elysian Island", 338.2f, -2715.9f, 38.5f },
	{ "Far North San Andreas", 24.775f, 7644.102f, 19.055f },
	{ "Ferris Wheel", -1670.7f, -1125.0f, 13.0f },
	{ "Fort Zancudo", -2047.4f, 3132.1f, 32.8f },
	{ "Fort Zancudo ATC Entrance", -2344.373f, 3267.498f, 32.811f },
	{ "Fort Zancudo ATC Top Floor", -2358.132f, 3249.754f, 101.451f },
	{ "God's Thumb", -1006.402f, 6272.383f, 1.503f },
	{ "Hippy Camp", 2476.712f, 3789.645f, 41.226f },
	{ "Jetsam", 760.4f, -2943.2f, 5.8f },
	{ "Jolene Cranley-Evans Ghost", 3059.620f, 5564.246f, 197.091f },
	{ "Kortz Center", -2243.810f, 264.048f, 174.615f },
	{ "Main LS Customs", -365.425f, -131.809f, 37.873f },
	{ "Marlowe Vineyards", -1868.971f, 2095.674f, 139.115f },
	{ "McKenzie Airfield", 2121.7f, 4796.3f, 41.1f },
	{ "Merryweather Dock", 486.417f, -3339.692f, 6.070f },
	{ "Mineshaft", -595.342f, 2086.008f, 131.412f },
	{ "Mt. Chiliad", 425.4f, 5614.3f, 766.5f },
	{ "Mt. Chiliad Summit", 450.718f, 5566.614f, 806.183f },
	{ "NOOSE Headquarters", 2535.243f, -383.799f, 92.993f },
	{ "Pacific Standard Bank", 235.046f, 216.434f, 106.287f },
	{ "Paleto Bay Pier", -275.522f, 6635.835f, 7.425f },
	{ "Playboy Mansion", -1475.234f, 167.088f, 55.841f },
	{ "Police Station", 436.491f, -982.172f, 30.699f },
	{ "Quarry", 2954.196f, 2783.410f, 41.004f },
	{ "Sandy Shores Airfield", 1747.0f, 3273.7f, 41.1f },
	{ "Satellite Dishes", 2062.123f, 2942.055f, 47.431f },
	{ "Sisyphus Theater Stage", 686.245f, 577.950f, 130.461f },
	{ "Trevor's Meth Lab", 1391.773f, 3608.716f, 38.942f },
	{ "Weed Farm", 2208.777f, 5578.235f, 53.735f },
	{ "Wind Farm", 2354.0f, 1830.3f, 101.1f }
};

const std::vector<WeatherTypesStruct> Cheat::GameArrays::WeatherTypes = {
	{ "Extra Sunny",	"EXTRASUNNY" },
	{ "Sunny",			"CLEAR" },
	{ "Cloudy",			"CLOUDS" },
	{ "Smoggy",			"SMOG" },
	{ "Foggy",			"FOGGY" },
	{ "Overcast",		"OVERCAST" },
	{ "Stormy",			"THUNDER" },
	{ "Snow",			"SNOW" },
	{ "Snowlight",		"SNOWLIGHT" },
	{ "Blizzard",		"BLIZZARD" }
};

//This only contains the most expensive/'best' weapon components
const std::vector<MaxUpgradeWeaponComponentsStruct> Cheat::GameArrays::MaxUpgradeWeaponComponents = {
	{ 0xD8DF3C3C, "COMPONENT_KNUCKLE_VARMOD_VAGOS" },
	{ 0xDFE37640, "COMPONENT_SWITCHBLADE_VARMOD_VAR1" },
	{ 0x1B06D571, "COMPONENT_PISTOL_CLIP_02" },
	{ 0x1B06D571, "COMPONENT_AT_PI_FLSH" },
	{ 0x1B06D571, "COMPONENT_AT_PI_SUPP_02" },
	{ 0x1B06D571, "COMPONENT_PISTOL_VARMOD_LUXE" },
	{ 0x5EF9FEC4, "COMPONENT_COMBATPISTOL_CLIP_02" },
	{ 0x5EF9FEC4, "COMPONENT_AT_PI_FLSH" },
	{ 0x5EF9FEC4, "COMPONENT_AT_PI_SUPP" },
	{ 0x5EF9FEC4, "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER" },
	{ 0x22D8FE39, "COMPONENT_APPISTOL_CLIP_02" },
	{ 0x22D8FE39, "COMPONENT_AT_PI_FLSH" },
	{ 0x22D8FE39, "COMPONENT_APPISTOL_VARMOD_LUXE" },
	{ 0x99AEEB3B, "COMPONENT_PISTOL50_CLIP_02" },
	{ 0x99AEEB3B, "COMPONENT_AT_PI_FLSH" },
	{ 0x99AEEB3B, "COMPONENT_AT_AR_SUPP_02" },
	{ 0x99AEEB3B, "COMPONENT_PISTOL50_VARMOD_LUXE" },
	{ 0xC1B3C3D1, "COMPONENT_REVOLVER_VARMOD_BOSS" },
	{ 0xBFD21232, "COMPONENT_SNSPISTOL_CLIP_02" },
	{ 0xBFD21232, "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER" },
	{ 0xD205520E, "COMPONENT_HEAVYPISTOL_CLIP_02" },
	{ 0xD205520E, "COMPONENT_AT_PI_FLSH" },
	{ 0xD205520E, "COMPONENT_AT_PI_SUPP" },
	{ 0xD205520E, "COMPONENT_HEAVYPISTOL_VARMOD_LUXE" },
	{ 0xCB96392F, "COMPONENT_REVOLVER_MK2_CLIP_FMJ" },
	{ 0xCB96392F, "COMPONENT_AT_SCOPE_MACRO_MK2" },
	{ 0xCB96392F, "COMPONENT_AT_PI_FLSH" },
	{ 0xCB96392F, "COMPONENT_AT_PI_COMP_03" },
	{ 0xCB96392F, "COMPONENT_REVOLVER_MK2_CAMO_IND_01" },
	{ 0x88374054, "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ" },
	{ 0x88374054, "COMPONENT_AT_PI_FLSH_03" },
	{ 0x88374054, "COMPONENT_AT_PI_RAIL_02" },
	{ 0x88374054, "COMPONENT_AT_PI_SUPP_02" },
	{ 0x88374054, "COMPONENT_AT_PI_COMP_02" },
	{ 0x88374054, "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE" },
	{ 0xBFE256D4, "COMPONENT_PISTOL_MK2_CLIP_02" },
	{ 0xBFE256D4, "COMPONENT_PISTOL_MK2_CLIP_FMJ" },
	{ 0xBFE256D4, "COMPONENT_AT_PI_RAIL" },
	{ 0xBFE256D4, "COMPONENT_AT_PI_FLSH_02" },
	{ 0xBFE256D4, "COMPONENT_AT_PI_SUPP_02" },
	{ 0xBFE256D4, "COMPONENT_AT_PI_COMP" },
	{ 0xBFE256D4, "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE" },
	{ 0x83839C4, "COMPONENT_VINTAGEPISTOL_CLIP_02" },
	{ 0x83839C4, "COMPONENT_AT_PI_SUPP" },
	{ 0xAF3696A1, "COMPONENT_RAYPISTOL_VARMOD_XMAS18" },
	{ 0x2B5EF5EC, "COMPONENT_CERAMICPISTOL_CLIP_02" },
	{ 0x2B5EF5EC, "COMPONENT_CERAMICPISTOL_SUPP" },
	{ 0x13532244, "COMPONENT_MICROSMG_CLIP_02" },
	{ 0x13532244, "COMPONENT_AT_PI_FLSH" },
	{ 0x13532244, "COMPONENT_AT_SCOPE_MACRO" },
	{ 0x13532244, "COMPONENT_AT_AR_SUPP_02" },
	{ 0x13532244, "COMPONENT_MICROSMG_VARMOD_LUXE" },
	{ 0x2BE6766B, "COMPONENT_SMG_CLIP_03" },
	{ 0x2BE6766B, "COMPONENT_AT_AR_FLSH" },
	{ 0x2BE6766B, "COMPONENT_AT_SCOPE_MACRO_02" },
	{ 0x2BE6766B, "COMPONENT_AT_PI_SUPP" },
	{ 0x2BE6766B, "COMPONENT_SMG_VARMOD_LUXE" },
	{ 0xEFE7E2DF, "COMPONENT_ASSAULTSMG_CLIP_02" },
	{ 0xEFE7E2DF, "COMPONENT_AT_AR_FLSH" },
	{ 0xEFE7E2DF, "COMPONENT_AT_SCOPE_MACRO" },
	{ 0xEFE7E2DF, "COMPONENT_AT_AR_SUPP_02" },
	{ 0xEFE7E2DF, "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER" },
	{ 0xBD248B55, "COMPONENT_MINISMG_CLIP_02" },
	{ 0x78A97CD0, "COMPONENT_SMG_MK2_CLIP_02" },
	{ 0x78A97CD0, "COMPONENT_SMG_MK2_CLIP_FMJ" },
	{ 0x78A97CD0, "COMPONENT_AT_AR_FLSH" },
	{ 0x78A97CD0, "COMPONENT_AT_SIGHTS_SMG" },
	{ 0x78A97CD0, "COMPONENT_AT_SCOPE_SMALL_SMG_MK2" },
	{ 0x78A97CD0, "COMPONENT_AT_PI_SUPP" },
	{ 0x78A97CD0, "COMPONENT_AT_MUZZLE_07" },
	{ 0x78A97CD0, "COMPONENT_AT_SB_BARREL_02" },
	{ 0x78A97CD0, "COMPONENT_SMG_MK2_CAMO_IND_01" },
	{ 0xDB1AA450, "COMPONENT_MACHINEPISTOL_CLIP_02" },
	{ 0xDB1AA450, "COMPONENT_MACHINEPISTOL_CLIP_03" },
	{ 0xDB1AA450, "COMPONENT_AT_PI_SUPP" },
	{ 0x0A3D4D34, "COMPONENT_COMBATPDW_CLIP_03" },
	{ 0x0A3D4D34, "COMPONENT_AT_AR_FLSH" },
	{ 0x0A3D4D34, "COMPONENT_AT_AR_AFGRIP" },
	{ 0x0A3D4D34, "COMPONENT_AT_SCOPE_SMALL" },
	{ 0x1D073A89, "COMPONENT_AT_AR_FLSH" },
	{ 0x1D073A89, "COMPONENT_AT_SR_SUPP" },
	{ 0x1D073A89, "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER" },
	{ 0x7846A318, "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE" },
	{ 0xE284C527, "COMPONENT_ASSAULTSHOTGUN_CLIP_02" },
	{ 0xE284C527, "COMPONENT_AT_AR_FLSH" },
	{ 0xE284C527, "COMPONENT_AT_AR_SUPP" },
	{ 0xE284C527, "COMPONENT_AT_AR_AFGRIP" },
	{ 0x9D61E50F, "COMPONENT_AT_AR_FLSH" },
	{ 0x9D61E50F, "COMPONENT_AT_AR_SUPP_02" },
	{ 0x9D61E50F, "COMPONENT_AT_AR_AFGRIP" },
	{ 0x555AF99A, "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE" },
	{ 0x555AF99A, "COMPONENT_AT_SIGHTS" },
	{ 0x555AF99A, "COMPONENT_AT_SCOPE_SMALL_MK2" },
	{ 0x555AF99A, "COMPONENT_AT_AR_FLSH" },
	{ 0x555AF99A, "COMPONENT_AT_SR_SUPP_03" },
	{ 0x555AF99A, "COMPONENT_AT_MUZZLE_08" },
	{ 0x555AF99A, "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01" },
	{ 0x3AABBBAA, "COMPONENT_HEAVYSHOTGUN_CLIP_03" },
	{ 0x3AABBBAA, "COMPONENT_AT_AR_FLSH" },
	{ 0x3AABBBAA, "COMPONENT_AT_AR_SUPP_02" },
	{ 0x3AABBBAA, "COMPONENT_AT_AR_AFGRIP" },
	{ 0x5A96BA4, "COMPONENT_AT_AR_FLSH" },
	{ 0x5A96BA4, "COMPONENT_AT_AR_SUPP" },
	{ 0xBFEFFF6D, "COMPONENT_ASSAULTRIFLE_CLIP_03" },
	{ 0xBFEFFF6D, "COMPONENT_AT_AR_FLSH" },
	{ 0xBFEFFF6D, "COMPONENT_AT_SCOPE_MACRO" },
	{ 0xBFEFFF6D, "COMPONENT_AT_AR_SUPP_02" },
	{ 0xBFEFFF6D, "COMPONENT_AT_AR_AFGRIP" },
	{ 0xBFEFFF6D, "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE" },
	{ 0x83BF0278, "COMPONENT_CARBINERIFLE_CLIP_03" },
	{ 0x83BF0278, "COMPONENT_AT_AR_FLSH" },
	{ 0x83BF0278, "COMPONENT_AT_SCOPE_MEDIUM" },
	{ 0x83BF0278, "COMPONENT_AT_AR_SUPP" },
	{ 0x83BF0278, "COMPONENT_AT_AR_AFGRIP" },
	{ 0x83BF0278, "COMPONENT_CARBINERIFLE_VARMOD_LUXE" },
	{ 0xAF113F99, "COMPONENT_ADVANCEDRIFLE_CLIP_02" },
	{ 0xAF113F99, "COMPONENT_AT_AR_FLSH" },
	{ 0xAF113F99, "COMPONENT_AT_SCOPE_SMALL" },
	{ 0xAF113F99, "COMPONENT_AT_AR_SUPP" },
	{ 0xAF113F99, "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE" },
	{ 0xC0A3098D, "COMPONENT_SPECIALCARBINE_CLIP_03" },
	{ 0xC0A3098D, "COMPONENT_AT_AR_FLSH" },
	{ 0xC0A3098D, "COMPONENT_AT_SCOPE_MEDIUM" },
	{ 0xC0A3098D, "COMPONENT_AT_AR_SUPP_02" },
	{ 0xC0A3098D, "COMPONENT_AT_AR_AFGRIP" },
	{ 0xC0A3098D, "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER" },
	{ 0x7F229F94, "COMPONENT_BULLPUPRIFLE_CLIP_02" },
	{ 0x7F229F94, "COMPONENT_AT_AR_FLSH" },
	{ 0x7F229F94, "COMPONENT_AT_SCOPE_SMALL" },
	{ 0x7F229F94, "COMPONENT_AT_AR_SUPP" },
	{ 0x7F229F94, "COMPONENT_AT_AR_AFGRIP" },
	{ 0x7F229F94, "COMPONENT_BULLPUPRIFLE_VARMOD_LOW" },
	{ 0x84D6FAFD, "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02" },
	{ 0x84D6FAFD, "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ" },
	{ 0x84D6FAFD, "COMPONENT_AT_AR_FLSH" },
	{ 0x84D6FAFD, "COMPONENT_AT_SIGHTS" },
	{ 0x84D6FAFD, "COMPONENT_AT_SCOPE_SMALL_MK2" },
	{ 0x84D6FAFD, "COMPONENT_AT_BP_BARREL_02" },
	{ 0x84D6FAFD, "COMPONENT_AT_AR_SUPP" },
	{ 0x84D6FAFD, "COMPONENT_AT_MUZZLE_07" },
	{ 0x84D6FAFD, "COMPONENT_AT_AR_AFGRIP_02" },
	{ 0x84D6FAFD, "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01" },
	{ 0x969C3D67, "COMPONENT_SPECIALCARBINE_MK2_CLIP_02" },
	{ 0x969C3D67, "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ" },
	{ 0x969C3D67, "COMPONENT_AT_AR_FLSH" },
	{ 0x969C3D67, "COMPONENT_AT_SIGHTS" },
	{ 0x969C3D67, "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ 0x969C3D67, "COMPONENT_AT_AR_SUPP_02" },
	{ 0x969C3D67, "COMPONENT_AT_MUZZLE_07" },
	{ 0x969C3D67, "COMPONENT_AT_AR_AFGRIP_02" },
	{ 0x969C3D67, "COMPONENT_AT_SC_BARREL_02" },
	{ 0x969C3D67, "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01" },
	{ 0x394F415C, "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02" },
	{ 0x394F415C, "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ" },
	{ 0x394F415C, "COMPONENT_AT_AR_AFGRIP_02" },
	{ 0x394F415C, "COMPONENT_AT_AR_FLSH" },
	{ 0x394F415C, "COMPONENT_AT_SIGHTS" },
	{ 0x394F415C, "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ 0x394F415C, "COMPONENT_AT_AR_SUPP_02" },
	{ 0x394F415C, "COMPONENT_AT_MUZZLE_07" },
	{ 0x394F415C, "COMPONENT_AT_AR_BARREL_02" },
	{ 0x394F415C, "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01" },
	{ 0xFAD1F1C9, "COMPONENT_CARBINERIFLE_MK2_CLIP_02" },
	{ 0xFAD1F1C9, "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ" },
	{ 0xFAD1F1C9, "COMPONENT_AT_AR_AFGRIP_02" },
	{ 0xFAD1F1C9, "COMPONENT_AT_AR_FLSH" },
	{ 0xFAD1F1C9, "COMPONENT_AT_SIGHTS" },
	{ 0xFAD1F1C9, "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ 0xFAD1F1C9, "COMPONENT_AT_AR_SUPP" },
	{ 0xFAD1F1C9, "COMPONENT_AT_MUZZLE_07" },
	{ 0xFAD1F1C9, "COMPONENT_AT_CR_BARREL_02" },
	{ 0xFAD1F1C9, "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01" },
	{ 0x624FE830, "COMPONENT_COMPACTRIFLE_CLIP_03" },
	{ 0x9D1F17E6, "COMPONENT_MILITARYRIFLE_CLIP_02" },
	{ 0x9D1F17E6, "COMPONENT_AT_SCOPE_SMALL" },
	{ 0x9D1F17E6, "COMPONENT_AT_AR_FLSH" },
	{ 0x9D1F17E6, "COMPONENT_AT_AR_SUPP" },
	{ 0x9D07F764, "COMPONENT_MG_CLIP_02" },
	{ 0x9D07F764, "COMPONENT_AT_SCOPE_SMALL_02" },
	{ 0x9D07F764, "COMPONENT_MG_VARMOD_LOWRIDER" },
	{ 0x7FD62962, "COMPONENT_COMBATMG_CLIP_02" },
	{ 0x7FD62962, "COMPONENT_AT_SCOPE_MEDIUM" },
	{ 0x7FD62962, "COMPONENT_AT_AR_AFGRIP" },
	{ 0x7FD62962, "COMPONENT_COMBATMG_VARMOD_LOWRIDER" },
	{ 0xDBBD7280, "COMPONENT_COMBATMG_MK2_CLIP_02" },
	{ 0xDBBD7280, "COMPONENT_COMBATMG_MK2_CLIP_FMJ" },
	{ 0xDBBD7280, "COMPONENT_AT_AR_AFGRIP_02" },
	{ 0xDBBD7280, "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ 0xDBBD7280, "COMPONENT_AT_MUZZLE_07" },
	{ 0xDBBD7280, "COMPONENT_AT_MG_BARREL_02" },
	{ 0xDBBD7280, "COMPONENT_COMBATMG_MK2_CAMO_IND_01" },
	{ 0x61012683, "COMPONENT_GUSENBERG_CLIP_02" },
	{ 0x05FC3C11, "COMPONENT_SNIPERRIFLE_CLIP_01" },
	{ 0x05FC3C11, "COMPONENT_AT_AR_SUPP_02" },
	{ 0x05FC3C11, "COMPONENT_AT_SCOPE_MAX" },
	{ 0x05FC3C11, "COMPONENT_SNIPERRIFLE_VARMOD_LUXE" },
	{ 0x0C472FE2, "COMPONENT_HEAVYSNIPER_CLIP_01" },
	{ 0x0C472FE2, "COMPONENT_AT_SCOPE_MAX" },
	{ 0x6A6C02E0, "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02" },
	{ 0x6A6C02E0, "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ" },
	{ 0x6A6C02E0, "COMPONENT_AT_SCOPE_MEDIUM_MK2" },
	{ 0x6A6C02E0, "COMPONENT_AT_AR_FLSH" },
	{ 0x6A6C02E0, "COMPONENT_AT_AR_SUPP" },
	{ 0x6A6C02E0, "COMPONENT_AT_MUZZLE_07" },
	{ 0x6A6C02E0, "COMPONENT_AT_MRFL_BARREL_02" },
	{ 0x6A6C02E0, "COMPONENT_AT_AR_AFGRIP_02" },
	{ 0x6A6C02E0, "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01" },
	{ 0xA914799, "COMPONENT_HEAVYSNIPER_MK2_CLIP_02" },
	{ 0xA914799, "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE" },
	{ 0xA914799, "COMPONENT_AT_SCOPE_THERMAL" },
	{ 0xA914799, "COMPONENT_AT_MUZZLE_09" },
	{ 0xA914799, "COMPONENT_AT_SR_BARREL_02" },
	{ 0xA914799, "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01" },
	{ 0xC734385A, "COMPONENT_MARKSMANRIFLE_CLIP_02" },
	{ 0xC734385A, "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM" },
	{ 0xC734385A, "COMPONENT_AT_AR_FLSH" },
	{ 0xC734385A, "COMPONENT_AT_AR_SUPP" },
	{ 0xC734385A, "COMPONENT_AT_AR_AFGRIP" },
	{ 0xC734385A, "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE" },
	{ 0xA284510B, "COMPONENT_GRENADELAUNCHER_CLIP_01" },
	{ 0xA284510B, "COMPONENT_AT_AR_FLSH" },
	{ 0xA284510B, "COMPONENT_AT_AR_AFGRIP" },
	{ 0xA284510B, "COMPONENT_AT_SCOPE_SMALL" }
};

const std::vector<AnimationsStruct> Cheat::GameArrays::Animations = {
	{ "rcmpaparazzo_2", "shag_loop_poppy" },
	{ "rcmpaparazzo_2", "shag_loop_a" },
	{ "mini@strip_club@private_dance@part1", "priv_dance_p1" },
	{ "mini@strip_club@pole_dance@pole_dance1", "pd_dance_01" },
	{ "amb@world_human_push_ups@male@base", "base" },
	{ "amb@world_human_sit_ups@male@base", "base" },
	{ "rcmfanatic1celebrate", "celebrate" },
	{ "ragdoll@human", "electrocute" },
	{ "mp_suicide", "pistol" },
	{ "mp_suicide", "pill" },
	{ "mp_safehouseshower@male@", "male_shower_idle_b" }
};
const std::vector<std::string> Cheat::GameArrays::AnimationsDisplayNames = {
	"Sex Receiver", 
	"Sex Giver", 
	"Stripper Dance",
	"Pole Dance", 
	"Push Ups", 
	"Sit Ups",
	"Celebrate",
	"Electrocution",
	"Suicide (Pistol)",
	"Suicide (Pill)",
	"Showering"
};

const std::vector<std::string> Cheat::GameArrays::Scenarios = {
	"WORLD_HUMAN_AA_COFFEE",
	"WORLD_HUMAN_AA_SMOKE",
	"WORLD_HUMAN_BINOCULARS",
	"WORLD_HUMAN_BUM_FREEWAY",
	"WORLD_HUMAN_BUM_SLUMPED",
	"WORLD_HUMAN_BUM_STANDING",
	"WORLD_HUMAN_BUM_WASH",
	"WORLD_HUMAN_CAR_PARK_ATTENDANT",
	"WORLD_HUMAN_CHEERING",
	"WORLD_HUMAN_CLIPBOARD",
	"WORLD_HUMAN_CONST_DRILL",
	"WORLD_HUMAN_COP_IDLES",
	"WORLD_HUMAN_DRINKING",
	"WORLD_HUMAN_DRUG_DEALER",
	"WORLD_HUMAN_DRUG_DEALER_HARD",
	"WORLD_HUMAN_MOBILE_FILM_SHOCKING",
	"WORLD_HUMAN_GARDENER_LEAF_BLOWER",
	"WORLD_HUMAN_GARDENER_PLANT",
	"WORLD_HUMAN_GOLF_PLAYER",
	"WORLD_HUMAN_GUARD_PATROL",
	"WORLD_HUMAN_GUARD_STAND",
	"WORLD_HUMAN_GUARD_STAND_ARMY",
	"WORLD_HUMAN_HAMMERING",
	"WORLD_HUMAN_HANG_OUT_STREET",
	"WORLD_HUMAN_HIKER",
	"WORLD_HUMAN_HIKER_STANDING",
	"WORLD_HUMAN_HUMAN_STATUE",
	"WORLD_HUMAN_JANITOR",
	"WORLD_HUMAN_JOG",
	"WORLD_HUMAN_JOG_STANDING",
	"WORLD_HUMAN_LEANING",
	"WORLD_HUMAN_MAID_CLEAN",
	"WORLD_HUMAN_MUSCLE_FLEX",
	"WORLD_HUMAN_MUSCLE_FREE_WEIGHTS",
	"WORLD_HUMAN_MUSICIAN",
	"WORLD_HUMAN_PAPARAZZI",
	"WORLD_HUMAN_PARTYING",
	"WORLD_HUMAN_PICNIC",
	"WORLD_HUMAN_POWER_WALKER",
	"WORLD_HUMAN_PROSTITUTE_HIGH_CLASS",
	"WORLD_HUMAN_PROSTITUTE_LOW_CLASS",
	"WORLD_HUMAN_PUSH_UPS",
	"WORLD_HUMAN_SEAT_LEDGE",
	"WORLD_HUMAN_SEAT_LEDGE_EATING",
	"WORLD_HUMAN_SEAT_STEPS",
	"WORLD_HUMAN_SEAT_WALL",
	"WORLD_HUMAN_SEAT_WALL_EATING",
	"WORLD_HUMAN_SEAT_WALL_TABLET",
	"WORLD_HUMAN_SECURITY_SHINE_TORCH",
	"WORLD_HUMAN_SIT_UPS",
	"WORLD_HUMAN_SMOKING",
	"WORLD_HUMAN_SMOKING_POT",
	"WORLD_HUMAN_STAND_FIRE",
	"WORLD_HUMAN_STAND_FISHING",
	"WORLD_HUMAN_STAND_IMPATIENT",
	"WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT",
	"WORLD_HUMAN_STAND_MOBILE",
	"WORLD_HUMAN_STAND_MOBILE_UPRIGHT",
	"WORLD_HUMAN_STRIP_WATCH_STAND",
	"WORLD_HUMAN_STUPOR",
	"WORLD_HUMAN_SUNBATHE",
	"WORLD_HUMAN_SUNBATHE_BACK",
	"WORLD_HUMAN_SUPERHERO",
	"WORLD_HUMAN_SWIMMING",
	"WORLD_HUMAN_TENNIS_PLAYER",
	"WORLD_HUMAN_TOURIST_MAP",
	"WORLD_HUMAN_TOURIST_MOBILE",
	"WORLD_HUMAN_VEHICLE_MECHANIC",
	"WORLD_HUMAN_WELDING",
	"WORLD_HUMAN_WINDOW_SHOP_BROWSE",
	"WORLD_HUMAN_YOGA",
	"Walk",
	"WORLD_BOAR_GRAZING",
	"WORLD_CAT_SLEEPING_GROUND",
	"WORLD_CAT_SLEEPING_LEDGE",
	"WORLD_COW_GRAZING",
	"WORLD_COYOTE_HOWL",
	"WORLD_COYOTE_REST",
	"WORLD_COYOTE_WANDER",
	"WORLD_COYOTE_WALK",
	"WORLD_CHICKENHAWK_FEEDING",
	"WORLD_CHICKENHAWK_STANDING",
	"WORLD_CORMORANT_STANDING",
	"WORLD_CROW_FEEDING",
	"WORLD_CROW_STANDING",
	"WORLD_DEER_GRAZING",
	"WORLD_DOG_BARKING_ROTTWEILER",
	"WORLD_DOG_BARKING_RETRIEVER",
	"WORLD_DOG_BARKING_SHEPHERD",
	"WORLD_DOG_SITTING_ROTTWEILER",
	"WORLD_DOG_SITTING_RETRIEVER",
	"WORLD_DOG_SITTING_SHEPHERD",
	"WORLD_DOG_BARKING_SMALL",
	"WORLD_DOG_SITTING_SMALL",
	"WORLD_DOLPHIN_SWIM",
	"WORLD_FISH_FLEE",
	"WORLD_FISH_IDLE",
	"WORLD_GULL_FEEDING",
	"WORLD_GULL_STANDING",
	"WORLD_HEN_FLEE",
	"WORLD_HEN_PECKING",
	"WORLD_HEN_STANDING",
	"WORLD_MOUNTAIN_LION_REST",
	"WORLD_MOUNTAIN_LION_WANDER",
	"WORLD_ORCA_SWIM",
	"WORLD_PIG_GRAZING",
	"WORLD_PIGEON_FEEDING",
	"WORLD_PIGEON_STANDING",
	"WORLD_RABBIT_EATING",
	"WORLD_RABBIT_FLEE",
	"WORLD_RATS_EATING",
	"WORLD_RATS_FLEEING",
	"WORLD_SHARK_SWIM",
	"WORLD_SHARK_HAMMERHEAD_SWIM",
	"WORLD_STINGRAY_SWIM",
	"WORLD_WHALE_SWIM",
	"DRIVE",
	"WORLD_VEHICLE_ATTRACTOR",
	"PARK_VEHICLE",
	"WORLD_VEHICLE_AMBULANCE",
	"WORLD_VEHICLE_BICYCLE_BMX",
	"WORLD_VEHICLE_BICYCLE_BMX_BALLAS",
	"WORLD_VEHICLE_BICYCLE_BMX_FAMILY",
	"WORLD_VEHICLE_BICYCLE_BMX_HARMONY",
	"WORLD_VEHICLE_BICYCLE_BMX_VAGOS",
	"WORLD_VEHICLE_BICYCLE_MOUNTAIN",
	"WORLD_VEHICLE_BICYCLE_ROAD",
	"WORLD_VEHICLE_BIKE_OFF_ROAD_RACE",
	"WORLD_VEHICLE_BIKER",
	"WORLD_VEHICLE_BOAT_IDLE",
	"WORLD_VEHICLE_BOAT_IDLE_ALAMO",
	"WORLD_VEHICLE_BOAT_IDLE_MARQUIS",
	"WORLD_VEHICLE_BROKEN_DOWN",
	"WORLD_VEHICLE_BUSINESSMEN",
	"WORLD_VEHICLE_HELI_LIFEGUARD",
	"WORLD_VEHICLE_CLUCKIN_BELL_TRAILER",
	"WORLD_VEHICLE_CONSTRUCTION_SOLO",
	"WORLD_VEHICLE_CONSTRUCTION_PASSENGERS",
	"WORLD_VEHICLE_DRIVE_PASSENGERS",
	"WORLD_VEHICLE_DRIVE_PASSENGERS_LIMITED",
	"WORLD_VEHICLE_DRIVE_SOLO",
	"WORLD_VEHICLE_FARM_WORKER",
	"WORLD_VEHICLE_FIRE_TRUCK",
	"WORLD_VEHICLE_EMPTY",
	"WORLD_VEHICLE_MARIACHI",
	"WORLD_VEHICLE_MECHANIC",
	"WORLD_VEHICLE_MILITARY_PLANES_BIG",
	"WORLD_VEHICLE_MILITARY_PLANES_SMALL",
	"WORLD_VEHICLE_PARK_PARALLEL",
	"WORLD_VEHICLE_PARK_PERPENDICULAR_NOSE_IN",
	"WORLD_VEHICLE_PASSENGER_EXIT",
	"WORLD_VEHICLE_POLICE_BIKE",
	"WORLD_VEHICLE_POLICE_CAR",
	"WORLD_VEHICLE_POLICE_NEXT_TO_CAR",
	"WORLD_VEHICLE_QUARRY",
	"WORLD_VEHICLE_SALTON",
	"WORLD_VEHICLE_SALTON_DIRT_BIKE",
	"WORLD_VEHICLE_SECURITY_CAR",
	"WORLD_VEHICLE_STREETRACE",
	"WORLD_VEHICLE_TOURBUS",
	"WORLD_VEHICLE_TOURIST",
	"WORLD_VEHICLE_TANDL",
	"WORLD_VEHICLE_TRACTOR",
	"WORLD_VEHICLE_TRACTOR_BEACH",
	"WORLD_VEHICLE_TRUCK_LOGS",
	"WORLD_VEHICLE_TRUCKS_TRAILERS",
	"PROP_BIRD_IN_TREE",
	"WORLD_VEHICLE_DISTANT_EMPTY_GROUND",
	"PROP_BIRD_TELEGRAPH_POLE",
	"PROP_HUMAN_ATM",
	"PROP_HUMAN_BBQ",
	"PROP_HUMAN_BUM_BIN",
	"PROP_HUMAN_BUM_SHOPPING_CART",
	"PROP_HUMAN_MUSCLE_CHIN_UPS",
	"PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY",
	"PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON",
	"PROP_HUMAN_PARKING_METER",
	"PROP_HUMAN_SEAT_ARMCHAIR",
	"PROP_HUMAN_SEAT_BAR",
	"PROP_HUMAN_SEAT_BENCH",
	"PROP_HUMAN_SEAT_BENCH_DRINK",
	"PROP_HUMAN_SEAT_BENCH_DRINK_BEER",
	"PROP_HUMAN_SEAT_BENCH_FOOD",
	"PROP_HUMAN_SEAT_BUS_STOP_WAIT",
	"PROP_HUMAN_SEAT_CHAIR",
	"PROP_HUMAN_SEAT_CHAIR_DRINK",
	"PROP_HUMAN_SEAT_CHAIR_DRINK_BEER",
	"PROP_HUMAN_SEAT_CHAIR_FOOD",
	"PROP_HUMAN_SEAT_CHAIR_UPRIGHT",
	"PROP_HUMAN_SEAT_CHAIR_MP_PLAYER",
	"PROP_HUMAN_SEAT_COMPUTER",
	"PROP_HUMAN_SEAT_DECKCHAIR",
	"PROP_HUMAN_SEAT_DECKCHAIR_DRINK",
	"PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS",
	"PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON",
	"PROP_HUMAN_SEAT_SEWING",
	"PROP_HUMAN_SEAT_STRIP_WATCH",
	"PROP_HUMAN_SEAT_SUNLOUNGER",
	"PROP_HUMAN_STAND_IMPATIENT",
	"CODE_HUMAN_COWER",
	"CODE_HUMAN_CROSS_ROAD_WAIT",
	"CODE_HUMAN_PARK_CAR",
	"PROP_HUMAN_MOVIE_BULB",
	"PROP_HUMAN_MOVIE_STUDIO_LIGHT",
	"CODE_HUMAN_MEDIC_KNEEL",
	"CODE_HUMAN_MEDIC_TEND_TO_DEAD",
	"CODE_HUMAN_MEDIC_TIME_OF_DEATH",
	"CODE_HUMAN_POLICE_CROWD_CONTROL",
	"CODE_HUMAN_POLICE_INVESTIGATE",
	"CHAINING_ENTRY",
	"CHAINING_EXIT",
	"CODE_HUMAN_STAND_COWER",
	"EAR_TO_TEXT",
	"EAR_TO_TEXT_FAT",
	"WORLD_LOOKAT_POINT"
};

const std::vector<TSEPropertyListStruct> Cheat::GameArrays::TSEPropertyList = {
	{ "Eclipse Towers", 1 },
	{ "Alta Street", 5 },
	{ "Del Perro Heights", 7 },
	{ "Power Street", 8 },
	{ "Spanish Avenue", 9 },
	{ "Las Lagunas Blvd", 10 },
	{ "Milton Road", 11 },
	{ "The Royale", 12 },
	{ "Milton Drive", 13 },
	{ "San Vitas Street", 18 },
	{ "Vespucci Blvd", 20 },
	{ "Cougar Avenue", 21 },
	{ "Prosperity Street", 22 }
};

const std::vector<std::string> Cheat::GameArrays::HUDColors = {
	"HUD_COLOUR_PURE_WHITE",
	"HUD_COLOUR_WHITE",
	"HUD_COLOUR_BLACK",
	"HUD_COLOUR_GREY",
	"HUD_COLOUR_GREYLIGHT",
	"HUD_COLOUR_GREYDARK",
	"HUD_COLOUR_RED",
	"HUD_COLOUR_REDLIGHT",
	"HUD_COLOUR_REDDARK",
	"HUD_COLOUR_BLUE",
	"HUD_COLOUR_BLUELIGHT",
	"HUD_COLOUR_BLUEDARK",
	"HUD_COLOUR_YELLOW",
	"HUD_COLOUR_YELLOWLIGHT",
	"HUD_COLOUR_YELLOWDARK",
	"HUD_COLOUR_ORANGE",
	"HUD_COLOUR_ORANGELIGHT",
	"HUD_COLOUR_ORANGEDARK",
	"HUD_COLOUR_GREEN",
	"HUD_COLOUR_GREENLIGHT",
	"HUD_COLOUR_GREENDARK",
	"HUD_COLOUR_PURPLE",
	"HUD_COLOUR_PURPLELIGHT",
	"HUD_COLOUR_PURPLEDARK",
	"HUD_COLOUR_PINK",
	"HUD_COLOUR_RADAR_HEALTH",
	"HUD_COLOUR_RADAR_ARMOUR",
	"HUD_COLOUR_RADAR_DAMAGE",
	"HUD_COLOUR_NET_PLAYER1",
	"HUD_COLOUR_NET_PLAYER2",
	"HUD_COLOUR_NET_PLAYER3",
	"HUD_COLOUR_NET_PLAYER4",
	"HUD_COLOUR_NET_PLAYER5",
	"HUD_COLOUR_NET_PLAYER6",
	"HUD_COLOUR_NET_PLAYER7",
	"HUD_COLOUR_NET_PLAYER8",
	"HUD_COLOUR_NET_PLAYER9",
	"HUD_COLOUR_NET_PLAYER10",
	"HUD_COLOUR_NET_PLAYER11",
	"HUD_COLOUR_NET_PLAYER12",
	"HUD_COLOUR_NET_PLAYER13",
	"HUD_COLOUR_NET_PLAYER14",
	"HUD_COLOUR_NET_PLAYER15",
	"HUD_COLOUR_NET_PLAYER16",
	"HUD_COLOUR_NET_PLAYER17",
	"HUD_COLOUR_NET_PLAYER18",
	"HUD_COLOUR_NET_PLAYER19",
	"HUD_COLOUR_NET_PLAYER20",
	"HUD_COLOUR_NET_PLAYER21",
	"HUD_COLOUR_NET_PLAYER22",
	"HUD_COLOUR_NET_PLAYER23",
	"HUD_COLOUR_NET_PLAYER24",
	"HUD_COLOUR_NET_PLAYER25",
	"HUD_COLOUR_NET_PLAYER26",
	"HUD_COLOUR_NET_PLAYER27",
	"HUD_COLOUR_NET_PLAYER28",
	"HUD_COLOUR_NET_PLAYER29",
	"HUD_COLOUR_NET_PLAYER30",
	"HUD_COLOUR_NET_PLAYER31",
	"HUD_COLOUR_NET_PLAYER32",
	"HUD_COLOUR_SIMPLEBLIP_DEFAULT",
	"HUD_COLOUR_MENU_BLUE",
	"HUD_COLOUR_MENU_GREY_LIGHT",
	"HUD_COLOUR_MENU_BLUE_EXTRA_DARK",
	"HUD_COLOUR_MENU_YELLOW",
	"HUD_COLOUR_MENU_YELLOW_DARK",
	"HUD_COLOUR_MENU_GREEN",
	"HUD_COLOUR_MENU_GREY",
	"HUD_COLOUR_MENU_GREY_DARK",
	"HUD_COLOUR_MENU_HIGHLIGHT",
	"HUD_COLOUR_MENU_STANDARD",
	"HUD_COLOUR_MENU_DIMMED",
	"HUD_COLOUR_MENU_EXTRA_DIMMED",
	"HUD_COLOUR_BRIEF_TITLE",
	"HUD_COLOUR_MID_GREY_MP",
	"HUD_COLOUR_NET_PLAYER1_DARK",
	"HUD_COLOUR_NET_PLAYER2_DARK",
	"HUD_COLOUR_NET_PLAYER3_DARK",
	"HUD_COLOUR_NET_PLAYER4_DARK",
	"HUD_COLOUR_NET_PLAYER5_DARK",
	"HUD_COLOUR_NET_PLAYER6_DARK",
	"HUD_COLOUR_NET_PLAYER7_DARK",
	"HUD_COLOUR_NET_PLAYER8_DARK",
	"HUD_COLOUR_NET_PLAYER9_DARK",
	"HUD_COLOUR_NET_PLAYER10_DARK",
	"HUD_COLOUR_NET_PLAYER11_DARK",
	"HUD_COLOUR_NET_PLAYER12_DARK",
	"HUD_COLOUR_NET_PLAYER13_DARK",
	"HUD_COLOUR_NET_PLAYER14_DARK",
	"HUD_COLOUR_NET_PLAYER15_DARK",
	"HUD_COLOUR_NET_PLAYER16_DARK",
	"HUD_COLOUR_NET_PLAYER17_DARK",
	"HUD_COLOUR_NET_PLAYER18_DARK",
	"HUD_COLOUR_NET_PLAYER19_DARK",
	"HUD_COLOUR_NET_PLAYER20_DARK",
	"HUD_COLOUR_NET_PLAYER21_DARK",
	"HUD_COLOUR_NET_PLAYER22_DARK",
	"HUD_COLOUR_NET_PLAYER23_DARK",
	"HUD_COLOUR_NET_PLAYER24_DARK",
	"HUD_COLOUR_NET_PLAYER25_DARK",
	"HUD_COLOUR_NET_PLAYER26_DARK",
	"HUD_COLOUR_NET_PLAYER27_DARK",
	"HUD_COLOUR_NET_PLAYER28_DARK",
	"HUD_COLOUR_NET_PLAYER29_DARK",
	"HUD_COLOUR_NET_PLAYER30_DARK",
	"HUD_COLOUR_NET_PLAYER31_DARK",
	"HUD_COLOUR_NET_PLAYER32_DARK",
	"HUD_COLOUR_BRONZE",
	"HUD_COLOUR_SILVER",
	"HUD_COLOUR_GOLD",
	"HUD_COLOUR_PLATINUM",
	"HUD_COLOUR_GANG1",
	"HUD_COLOUR_GANG2",
	"HUD_COLOUR_GANG3",
	"HUD_COLOUR_GANG4",
	"HUD_COLOUR_SAME_CREW",
	"HUD_COLOUR_FREEMODE",
	"HUD_COLOUR_PAUSE_BG",
	"HUD_COLOUR_FRIENDLY",
	"HUD_COLOUR_ENEMY",
	"HUD_COLOUR_LOCATION",
	"HUD_COLOUR_PICKUP",
	"HUD_COLOUR_PAUSE_SINGLEPLAYER",
	"HUD_COLOUR_FREEMODE_DARK",
	"HUD_COLOUR_INACTIVE_MISSION",
	"HUD_COLOUR_DAMAGE",
	"HUD_COLOUR_PINKLIGHT",
	"HUD_COLOUR_PM_MITEM_HIGHLIGHT",
	"HUD_COLOUR_SCRIPT_VARIABLE",
	"HUD_COLOUR_YOGA",
	"HUD_COLOUR_TENNIS",
	"HUD_COLOUR_GOLF",
	"HUD_COLOUR_SHOOTING_RANGE",
	"HUD_COLOUR_FLIGHT_SCHOOL",
	"HUD_COLOUR_NORTH_BLUE",
	"HUD_COLOUR_SOCIAL_CLUB",
	"HUD_COLOUR_PLATFORM_BLUE",
	"HUD_COLOUR_PLATFORM_GREEN",
	"HUD_COLOUR_PLATFORM_GREY",
	"HUD_COLOUR_FACEBOOK_BLUE",
	"HUD_COLOUR_INGAME_BG",
	"HUD_COLOUR_DARTS",
	"HUD_COLOUR_WAYPOINT",
	"HUD_COLOUR_MICHAEL",
	"HUD_COLOUR_FRANKLIN",
	"HUD_COLOUR_TREVOR",
	"HUD_COLOUR_GOLF_P1",
	"HUD_COLOUR_GOLF_P2",
	"HUD_COLOUR_GOLF_P3",
	"HUD_COLOUR_GOLF_P4",
	"HUD_COLOUR_WAYPOINTLIGHT",
	"HUD_COLOUR_WAYPOINTDARK",
	"HUD_COLOUR_PANEL_LIGHT",
	"HUD_COLOUR_MICHAEL_DARK",
	"HUD_COLOUR_FRANKLIN_DARK",
	"HUD_COLOUR_TREVOR_DARK",
	"HUD_COLOUR_OBJECTIVE_ROUTE",
	"HUD_COLOUR_PAUSEMAP_TINT",
	"HUD_COLOUR_PAUSE_DESELECT",
	"HUD_COLOUR_PM_WEAPONS_PURCHASABLE",
	"HUD_COLOUR_PM_WEAPONS_LOCKED",
	"HUD_COLOUR_END_SCREEN_BG",
	"HUD_COLOUR_CHOP",
	"HUD_COLOUR_PAUSEMAP_TINT_HALF",
	"HUD_COLOUR_NORTH_BLUE_OFFICIAL",
	"HUD_COLOUR_SCRIPT_VARIABLE_2",
	"HUD_COLOUR_H",
	"HUD_COLOUR_HDARK",
	"HUD_COLOUR_T",
	"HUD_COLOUR_TDARK",
	"HUD_COLOUR_HSHARD",
	"HUD_COLOUR_CONTROLLER_MICHAEL",
	"HUD_COLOUR_CONTROLLER_FRANKLIN",
	"HUD_COLOUR_CONTROLLER_TREVOR",
	"HUD_COLOUR_CONTROLLER_CHOP",
	"HUD_COLOUR_VIDEO_EDITOR_VIDEO",
	"HUD_COLOUR_VIDEO_EDITOR_AUDIO",
	"HUD_COLOUR_VIDEO_EDITOR_TEXT",
	"HUD_COLOUR_HB_BLUE",
	"HUD_COLOUR_HB_YELLOW",
	"HUD_COLOUR_VIDEO_EDITOR_SCORE",
	"HUD_COLOUR_VIDEO_EDITOR_AUDIO_FADEOUT",
	"HUD_COLOUR_VIDEO_EDITOR_TEXT_FADEOUT",
	"HUD_COLOUR_VIDEO_EDITOR_SCORE_FADEOUT",
	"HUD_COLOUR_HEIST_BACKGROUND",
	"HUD_COLOUR_VIDEO_EDITOR_AMBIENT",
	"HUD_COLOUR_VIDEO_EDITOR_AMBIENT_FADEOUT",
	"HUD_COLOUR_VIDEO_EDITOR_AMBIENT_DARK",
	"HUD_COLOUR_VIDEO_EDITOR_AMBIENT_LIGHT",
	"HUD_COLOUR_VIDEO_EDITOR_AMBIENT_MID",
	"HUD_COLOUR_LOW_FLOW",
	"HUD_COLOUR_LOW_FLOW_DARK",
	"HUD_COLOUR_G1",
	"HUD_COLOUR_G2",
	"HUD_COLOUR_G3",
	"HUD_COLOUR_G4",
	"HUD_COLOUR_G5",
	"HUD_COLOUR_G6",
	"HUD_COLOUR_G7",
	"HUD_COLOUR_G8",
	"HUD_COLOUR_G9",
	"HUD_COLOUR_G10",
	"HUD_COLOUR_G11",
	"HUD_COLOUR_G12",
	"HUD_COLOUR_G13",
	"HUD_COLOUR_G14",
	"HUD_COLOUR_G15",
	"HUD_COLOUR_ADVERSARY",
	"HUD_COLOUR_DEGEN_RED",
	"HUD_COLOUR_DEGEN_YELLOW",
	"HUD_COLOUR_DEGEN_GREEN",
	"HUD_COLOUR_DEGEN_CYAN",
	"HUD_COLOUR_DEGEN_BLUE",
	"HUD_COLOUR_DEGEN_MAGENTA",
	"HUD_COLOUR_STUNT_1",
	"HUD_COLOUR_STUNT_2",
	"HUD_COLOUR_SPECIAL_RACE_SERIES",
	"HUD_COLOUR_SPECIAL_RACE_SERIES_DARK",
	"HUD_COLOUR_CS",
	"HUD_COLOUR_CS_DARK",
	"HUD_COLOUR_TECH_GREEN",
	"HUD_COLOUR_TECH_GREEN_DARK",
	"HUD_COLOUR_TECH_RED",
	"HUD_COLOUR_TECH_GREEN_VERY_DARK"
};

// We call GET_HUD_COLOUR at initialization to fill this array with all game default HUD colors
std::vector<DefaultHUDColorsStruct> Cheat::GameArrays::DefaultHUDColors;
