#pragma once

namespace Cheat
{
	namespace GUI
	{
		namespace Submenus
		{
			void (*FunctionPointers[])();
			extern int NumberOfSubmenus;
			void Home();
			void Self();
			void AllPlayersExclusions();
			void AllPlayers();
			void Online();
			void Session();
			void SessionChat();
			void RecoverySubmenuWarning();
			void RecoveryStatistics();
			void Recovery();
			void ReportStatistics();
			void SelfModel();
			void SpawnedVehicles();
			void VehicleSpawn();
			void Spawn();
			void ObjectSpawn();
			void PlayerList();
			void PedSpawn();
			void DLCVehicles();
			void ThemeFiles();
			void Theme();
			void About();
			void Settings();
			void World();
			void NearbyPeds();
			void NearbyVehicles();
			void Time();
			void Vehicle();
			void VehicleCustomizer();
			void VehicleCustomizerColor();
			void VehicleCustomizerNeon();
			void VehicleMultipliers();
			void Miscellaneous();
			void Globals();
			void Vision();
			void HideElements();
			void Protections();
			void Wardrobe();
			void IPLLoader();
			void Weapons();
			void Weapon();
			void ShootEntities();
			void VehicleWeapons();
			void VehicleSpawnSettings();
			void Teleport();
			void HUD();
			void CustomTeleportLocations();
			void Weather();
			void ESP();
			void Radio();
			void WeaponVisuals();
			void Animations();
			void SelectedPlayerTeleport();
			void SelectedPlayer();
			void SelectedPlayerRemote();
			void SelectedPlayerApartmentTeleport();
			void SelectedPlayerAttachments();
			void SelectedPlayerFriendly();
			void SelectedPlayerGriefing();
			void Aimbot();
			void IPLTeleports();
			void WeaponAmmo();
			void LandmarkTeleportLocations();
			void SafehousesTeleportLocations();
			void HighAltitudeTeleportLocations();
			void UnderwaterTeleportLocations();
			void TheContractDLC();
			void LosSantosTunersDLC();
			void CayoPericoHeistDLC();
			void SummerSpecialDLC();
			void CunningStuntsDLC();
			void DiamondCasinoHeistDLC();
			void DiamondCasinoResortDLC();
			void ArenaWarDLC();
			void SmugglersRunDLC();
			void AfterHoursDLC();
			void TheCriminalEnterprisesDLC();
			void GunrunningDLC();
			void DoomsdayHeistDLC();
			void SSASSSDLC();
			void VanVehicles();
			void UtilityVehicles();
			void TrainVehicles();
			void TrailerVehicles();
			void SuperVehicles();
			void SportVehicles();
			void SUVVehicles();
			void ServiceVehicles();
			void PlaneVehicles();
			void MotorcycleVehicles();
			void MilitaryVehicles();
			void IndustrialVehicles();
			void HelicopterVehicles();
			void EmergencyVehicles();
			void SportClassicVehicles();
			void OffroadVehicles();
			void SedanVehicles();
			void CoupesVehicles();
			void MuscleVehicles();
			void BoatVehicles();
			void CommercialVehicles();
			void CompactVehicles();
			void CycleVehicles();
		}
	}
}